// apps/vue/src/components/miscellaneous/Collapse/CollapseExternal.vue
<!--
  CollapseExternal 원본 구현.
  컴포넌트 상태와 사용자 상호작용을 관리하고 공통 CSS 및 접근성 계약을 적용합니다.
-->
<script setup>
import { computed, onMounted, ref, useAttrs, useId, watch } from 'vue';
import { setSlideRegionOpen } from '@uxkm/interactions/slide-region';
import Button from '../../basic/Button/Button.vue';
import Icon from '../../basic/Icon/Icon.vue';

defineOptions({ name: 'UxkmCollapseExternal', inheritAttrs: false });

const props = defineProps({
  triggerLabel: { type: String, default: '' },
  open: Boolean,
  effect: String,
  boxed: { type: Boolean, default: true },
  ripple: { type: Boolean, default: true },
});
const attrs = useAttrs();
const panelId = `collapse-external-${useId().replaceAll(':', '')}`;
const panelRef = ref(null);
const isOpen = ref(Boolean(props.open));
const slide = computed(() => props.effect === 'slide');
const restAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
let firstSlideSync = true;

watch(
  [isOpen, slide],
  ([open, hasSlide]) => {
    if (!hasSlide) return;
    setSlideRegionOpen(panelRef.value, open, !firstSlideSync);
    firstSlideSync = false;
  },
  { flush: 'post' },
);

onMounted(() => {
  if (slide.value) {
    setSlideRegionOpen(panelRef.value, isOpen.value, false);
    firstSlideSync = false;
  }
});
</script>

<template>
  <div v-bind="restAttrs" :class="attrs.class">
    <div v-if="$slots.lead"><slot name="lead" /></div>
    <Button
      variant="ghost"
      size="sm"
      :expanded="isOpen"
      :aria-controls="panelId"
      :ripple="ripple"
      @click="isOpen = !isOpen"
    >
      {{ triggerLabel }}
      <template #icon-after><Icon name="chevron-down" size="sm" /></template>
    </Button>
    <div
      :id="panelId"
      ref="panelRef"
      class="collapse"
      :class="{ 'is-open': isOpen }"
      :data-effect="slide ? 'slide' : undefined"
      :hidden="slide ? undefined : !isOpen"
      :style="boxed ? { marginTop: 'var(--space-sm)' } : undefined"
    >
      <div :class="boxed ? 'collapse_inner' : undefined"><slot /></div>
    </div>
  </div>
</template>

// apps/svelte/src/components/miscellaneous/Collapse/CollapseExternal.svelte
<!--
  CollapseExternal 원본 구현.
  컴포넌트 상태와 사용자 상호작용을 관리하고 공통 CSS 및 접근성 계약을 적용합니다.
-->
<script>
import { onMount } from 'svelte';
import { setSlideRegionOpen } from '@uxkm/interactions/slide-region';
import Button from '../../basic/Button/Button.svelte';
import Icon from '../../basic/Icon/Icon.svelte';



let {
  triggerLabel = '',
  open = false,
  effect,
  boxed = true,
  ripple = true,
  children,
  iconBefore,
  iconAfter,
  prefix,
  suffix,
  panel,
  extra,
  badge,
  class: className,
  ...rest
} = $props();

const panelId = `collapse-external-${crypto.randomUUID().replaceAll('-', '')}`;
let panelRef = $state(null);
let isOpen = $state(Boolean(open));
let slide = $derived(effect === 'slide');
let restAttrs = $derived({
  const { class: _class, ...rest } = rest;
  return rest;
});
let firstSlideSync = true;

$effect(
  [isOpen, slide],
  ([open, hasSlide]) => {
    if (!hasSlide) return;
    setSlideRegionOpen(panelRef, open, !firstSlideSync);
    firstSlideSync = false;
  },
  { flush: 'post' },
);

onMount(() => {
  if (slide) {
    setSlideRegionOpen(panelRef, isOpen, false);
    firstSlideSync = false;
  }
});
</script>

<div {...restAttrs} class={attrs.class}>
    {#if lead}<div><slot name="lead" /></div>
    <Button
      variant="ghost"
      size="sm"
      expanded={isOpen}
      aria-controls={panelId}
      ripple={ripple}
      onclick={isOpen = !isOpen}
    >
      {{ triggerLabel }}
      <#icon-after><Icon name="chevron-down" size="sm" />
