// apps/nuxt/app/components/demo/DemoSection.vue
<template>
  <section class="section" :id="id" :aria-labelledby="`${id}-title`">
    <h2 :id="`${id}-title`">{{ title }}</h2>
    <p v-if="path"><code class="typo_code">{{ path }}</code></p>
    <div class="component_demo">
      <slot />
    </div>
  </section>
</template>

<script setup>
defineProps({
  id: { type: String, required: true },
  title: { type: String, required: true },
  path: { type: String, default: '' },
});
</script>

// apps/react/src/demo/DemoSection.jsx
export function DemoSection({ id, title, path, children }) {
  return (
    <section className="section" id={id} aria-labelledby={`${id}-title`}>
      <h2 id={`${id}-title`}>{title}</h2>
      {path ? <p><code className="typo_code">{path}</code></p> : null}
      <div className="component_demo">{children}</div>
    </section>
  );
}

export default DemoSection;
