// apps/vue/src/components/miscellaneous/Affix/Affix.vue
<!--
  Affix 원본 구현.
  컴포넌트 상태와 사용자 상호작용을 관리하고 공통 CSS 및 접근성 계약을 적용합니다.
-->
<script setup>
import { computed, onBeforeUnmount, onMounted, ref, useAttrs, watch } from 'vue';
import { initAffix } from '@uxkm/html/affix';

defineOptions({ name: 'UxkmAffix', inheritAttrs: false });
const props = defineProps({
  target: String, // 고정 기준 스크롤 컨테이너 선택자입니다.
  offsetTop: { type: [Number, String], default: 0 }, // 상단 고정 오프셋(px)입니다.
  offsetBottom: [Number, String], // 하단 고정 오프셋(px)입니다.
  skin: { type: String, default: '', validator: (value) => ['', 'bar', 'anchor'].includes(value) }, // bar · anchor 스킨입니다.
  interactive: { type: Boolean, default: true }, // 스크롤 고정을 활성화합니다.
});
const attrs = useAttrs();
const rootRef = ref(null);
let cleanup = null;
const classes = computed(() => ['affix', attrs.class].filter(Boolean));
const targetClasses = computed(() =>
  ['affix_target', props.skin && `affix_${props.skin}`].filter(Boolean),
);
const restAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
const dataAttrs = computed(() => ({
  'data-affix': props.interactive ? '' : undefined,
  'data-target': props.target || undefined,
  'data-offset-top': Number(props.offsetTop) !== 0 ? String(props.offsetTop) : undefined,
  'data-offset-bottom':
    props.offsetBottom !== undefined && props.offsetBottom !== null && props.offsetBottom !== ''
      ? String(props.offsetBottom)
      : undefined,
}));
function init() {
  cleanup?.();
  cleanup = props.interactive && rootRef.value ? initAffix(rootRef.value) : null;
}
onMounted(init);
watch(() => [props.interactive, props.target, props.offsetTop, props.offsetBottom], init, {
  flush: 'post',
});
onBeforeUnmount(() => cleanup?.());
</script>

<template>
  <div
    ref="rootRef"
    v-bind="{ ...restAttrs, ...dataAttrs }"
    :class="classes"
    data-component="Affix"
  >
    <div class="affix_placeholder" aria-hidden="true" hidden />
    <div :class="targetClasses"><slot /></div>
  </div>
</template>

// apps/svelte/src/components/miscellaneous/Affix/Affix.svelte
<!--
  Affix 원본 구현.
  컴포넌트 상태와 사용자 상호작용을 관리하고 공통 CSS 및 접근성 계약을 적용합니다.
-->
<script>
import { onMount, onDestroy } from 'svelte';
import { initAffix } from '@uxkm/html/affix';


let {
  target,
  offsetTop = 0,
  offsetBottom,
  skin = '',
  interactive = true,
  children,
  iconBefore,
  iconAfter,
  prefix,
  suffix,
  panel,
  extra,
  badge,
  class: className,
  ...rest
} = $props();입니다.
  offsetBottom: [Number, String], // 하단 고정 오프셋(px)입니다.
  skin: { type: String, default: '', validator: (value) => ['', 'bar', 'anchor'].includes(value) }, // bar · anchor 스킨입니다.
  interactive: { type: Boolean, default: true }, // 스크롤 고정을 활성화합니다.
});

let rootRef = $state(null);
let cleanup = null;
let classes = $derived(['affix', className].filter(Boolean));
let targetClasses = $derived(['affix_target', skin && `affix_${skin}`].filter(Boolean),
);
let restAttrs = $derived({
  const { class: _class, ...rest } = rest;
  return rest;
});
let dataAttrs = $derived(({
  'data-affix': interactive ? '' : undefined,
  'data-target': target || undefined,
  'data-offset-top': Number(offsetTop) !== 0 ? String(offsetTop) : undefined,
  'data-offset-bottom':
    offsetBottom !== undefined && offsetBottom !== null && offsetBottom !== ''
      ? String(offsetBottom)
      : undefined,
}));
function init() {
  cleanup?.();
  cleanup = interactive && rootRef ? initAffix(rootRef) : null;
}
onMount(init);
$effect(() => [interactive, target, offsetTop, offsetBottom], init, {
  flush: 'post',
});
onDestroy(() => cleanup?.());
</script>

<div
    bind:this={rootRef}
    v-bind="{ ...restAttrs, ...dataAttrs }"
    class={classes}
    data-component="Affix"
  >
    <div class="affix_placeholder" aria-hidden="true" hidden />
    <div class={targetClasses}>{@render children?.()}</div>
  </div>
