// apps/next/app/components/data-display/page.jsx
'use client';

import { Avatar, AvatarGroup } from '@uxkm/react/avatar';
import Badge from '@uxkm/react/badge';
import {
  Calendar,
  CalendarHeader,
  CalendarMonth,
  CalendarWeekdays,
} from '@uxkm/react/calendar';
import Card from '@uxkm/react/card';
import { List, ListItem } from '@uxkm/react/list';
import Stat from '@uxkm/react/stat';
import Table from '@uxkm/react/table';
import Tag from '@uxkm/react/tag';
import { Timeline, TimelineItem } from '@uxkm/react/timeline';
import { Tree, TreeNode } from '@uxkm/react/tree';
import Link from 'next/link';
import { DemoSection } from '../../../src/demo/DemoSection.jsx';

export default function DataDisplayPage() {
  return (
    <main className="guide_content">
      <div className="container container_lg">
        <header className="page_intro">
          <p className="color_accent size_sm">
            <Link href="/components" className="link color_accent">
              컴포넌트
            </Link>
            {' · Data Display'}
          </p>
          <h1>Data Display</h1>
          <p className="lead">데이터 표시 컴포넌트를 렌더합니다.</p>
        </header>

        <DemoSection id="avatar" title="Avatar" path="@uxkm/react/avatar">
          <AvatarGroup>
            <Avatar initials="AB" color="primary" />
            <Avatar initials="CD" color="success" />
          </AvatarGroup>
        </DemoSection>

        <DemoSection id="badge" title="Badge" path="@uxkm/react/badge">
          <Badge label="신규" />
        </DemoSection>

        <DemoSection id="tag" title="Tag" path="@uxkm/react/tag">
          <Tag label="태그" />
        </DemoSection>

        <DemoSection id="stat" title="Stat" path="@uxkm/react/stat">
          <Stat title="방문자" value="1,280" suffix="명" trend="+12%" trendColor="success" card />
        </DemoSection>

        <DemoSection id="card" title="Card" path="@uxkm/react/card">
          <Card title="카드 제목" subtitle="부제목">
            카드 본문 데모입니다.
          </Card>
        </DemoSection>

        <DemoSection id="list" title="List" path="@uxkm/react/list">
          <List bordered>
            <ListItem title="첫 번째 항목" description="설명 텍스트" />
            <ListItem title="두 번째 항목" description="설명 텍스트" />
          </List>
        </DemoSection>

        <DemoSection id="table" title="Table" path="@uxkm/react/table">
          <Table bordered>
            <thead>
              <tr>
                <th>이름</th>
                <th>역할</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>김민수</td>
                <td>디자이너</td>
              </tr>
              <tr>
                <td>이서연</td>
                <td>개발자</td>
              </tr>
            </tbody>
          </Table>
        </DemoSection>

        <DemoSection id="timeline" title="Timeline" path="@uxkm/react/timeline">
          <Timeline>
            <TimelineItem title="요청 접수" description="티켓이 생성되었습니다." time="09:00" active />
            <TimelineItem title="검토 중" description="담당자가 확인 중입니다." time="10:30" />
          </Timeline>
        </DemoSection>

        <DemoSection id="calendar" title="Calendar" path="@uxkm/react/calendar">
          <Calendar ariaLabel="데모 캘린더">
            <CalendarHeader title="2026년 9월" />
            <CalendarWeekdays />
            <CalendarMonth partial={14} selected={3} />
          </Calendar>
        </DemoSection>

        <DemoSection id="tree" title="Tree" path="@uxkm/react/tree">
          <Tree ariaLabel="데모 트리">
            <TreeNode label="문서" expanded>
              <TreeNode label="가이드" />
              <TreeNode label="API" />
            </TreeNode>
            <TreeNode label="설정" />
          </Tree>
        </DemoSection>

        <p>
          <Link href="/components" className="link color_primary">
            ← 컴포넌트 목록
          </Link>
        </p>
      </div>
    </main>
  );
}

// apps/nuxt/app/pages/components/data-display.vue
<template>
  <main class="guide_content">
    <div class="container container_lg">
      <header class="page_intro">
        <p class="color_accent size_sm">
          <NuxtLink class="link color_accent" to="/components">컴포넌트</NuxtLink>
          · Data Display
        </p>
        <h1>Data Display</h1>
        <p class="lead">데이터 표시 컴포넌트를 Vue로 렌더합니다.</p>
      </header>

      <DemoSection id="avatar" title="Avatar" path="@uxkm/vue/avatar">
        <AvatarGroup>
          <Avatar initials="UX" />
          <Avatar initials="KM" />
        </AvatarGroup>
      </DemoSection>

      <DemoSection id="badge" title="Badge" path="@uxkm/vue/badge">
        <Badge label="NEW" />
      </DemoSection>

      <DemoSection id="tag" title="Tag" path="@uxkm/vue/tag">
        <Tag label="Vue" />
      </DemoSection>

      <DemoSection id="stat" title="Stat" path="@uxkm/vue/stat">
        <Stat title="방문자" value="1,284" />
      </DemoSection>

      <DemoSection id="card" title="Card" path="@uxkm/vue/card">
        <Card title="카드 제목">카드 본문 데모입니다.</Card>
      </DemoSection>

      <DemoSection id="list" title="List" path="@uxkm/vue/list">
        <List bordered>
          <ListItem title="첫 번째 항목" description="설명 텍스트" />
          <ListItem title="두 번째 항목" description="설명 텍스트" />
        </List>
      </DemoSection>

      <DemoSection id="table" title="Table" path="@uxkm/vue/table">
        <Table bordered>
          <thead>
            <tr>
              <th>이름</th>
              <th>역할</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Kim</td>
              <td>Designer</td>
            </tr>
            <tr>
              <td>Lee</td>
              <td>Engineer</td>
            </tr>
          </tbody>
        </Table>
      </DemoSection>

      <DemoSection id="timeline" title="Timeline" path="@uxkm/vue/timeline">
        <Timeline>
          <TimelineItem title="생성" description="항목이 생성되었습니다." time="09:00" />
          <TimelineItem title="수정" description="내용이 업데이트되었습니다." time="12:30" />
        </Timeline>
      </DemoSection>

      <DemoSection id="calendar" title="Calendar" path="@uxkm/vue/calendar">
        <Calendar />
      </DemoSection>

      <DemoSection id="tree" title="Tree" path="@uxkm/vue/tree">
        <Tree>
          <TreeNode label="루트" expanded>
            <TreeNode label="자식 A" />
            <TreeNode label="자식 B" />
          </TreeNode>
        </Tree>
      </DemoSection>

      <p>
        <NuxtLink class="link color_primary" to="/components">← 컴포넌트 목록</NuxtLink>
      </p>
    </div>
  </main>
</template>

<script setup>
import Avatar, { AvatarGroup } from '@uxkm/vue/avatar';
import Badge from '@uxkm/vue/badge';
import Calendar from '@uxkm/vue/calendar';
import Card from '@uxkm/vue/card';
import List, { ListItem } from '@uxkm/vue/list';
import Stat from '@uxkm/vue/stat';
import Table from '@uxkm/vue/table';
import Tag from '@uxkm/vue/tag';
import Timeline, { TimelineItem } from '@uxkm/vue/timeline';
import Tree, { TreeNode } from '@uxkm/vue/tree';
import DemoSection from '../../components/demo/DemoSection.vue';
</script>
