// apps/next/app/components/layout/page.jsx
'use client';

import Container from '@uxkm/react/container';
import Divider from '@uxkm/react/divider';
import Flex, { FlexItem } from '@uxkm/react/flex';
import Grid, { GridCol } from '@uxkm/react/grid';
import Space from '@uxkm/react/space';
import Link from 'next/link';
import { DemoSection } from '../../../src/demo/DemoSection.jsx';

export default function LayoutPage() {
  return (
    <main className="guide_content">
      <div className="container container_lg">
        <header className="page_intro">
          <p className="color_accent size_sm">
            <Link href="/components" className="link color_accent">
              컴포넌트
            </Link>
            {' · Layout'}
          </p>
          <h1>Layout</h1>
          <p className="lead">레이아웃 컴포넌트를 렌더합니다.</p>
        </header>

        <DemoSection id="container" title="Container" path="@uxkm/react/container">
          <Container size="sm">Container 데모</Container>
        </DemoSection>

        <DemoSection id="divider" title="Divider" path="@uxkm/react/divider">
          <Divider label="구분선" />
        </DemoSection>

        <DemoSection id="flex" title="Flex" path="@uxkm/react/flex">
          <Flex gap="sm">
            <FlexItem>Item A</FlexItem>
            <FlexItem>Item B</FlexItem>
            <FlexItem>Item C</FlexItem>
          </Flex>
        </DemoSection>

        <DemoSection id="grid" title="Grid" path="@uxkm/react/grid">
          <Grid cols={3} gap="sm">
            <GridCol>Col 1</GridCol>
            <GridCol>Col 2</GridCol>
            <GridCol>Col 3</GridCol>
          </Grid>
        </DemoSection>

        <DemoSection id="space" title="Space" path="@uxkm/react/space">
          <Space gap="sm">
            <span>하나</span>
            <span>둘</span>
            <span>셋</span>
          </Space>
        </DemoSection>

        <p>
          <Link href="/components" className="link color_primary">
            ← 컴포넌트 목록
          </Link>
        </p>
      </div>
    </main>
  );
}

// apps/nuxt/app/pages/components/layout.vue
<template>
  <main class="guide_content">
    <div class="container container_lg">
      <header class="page_intro">
        <p class="color_accent size_sm">
          <NuxtLink class="link color_accent" to="/components">컴포넌트</NuxtLink>
          · Layout
        </p>
        <h1>Layout</h1>
        <p class="lead">레이아웃 컴포넌트를 Vue로 렌더합니다.</p>
      </header>

      <DemoSection id="container" title="Container" path="@uxkm/vue/container">
        <Container size="md">
          <p>Container 데모 콘텐츠</p>
        </Container>
      </DemoSection>

      <DemoSection id="divider" title="Divider" path="@uxkm/vue/divider">
        <Divider />
      </DemoSection>

      <DemoSection id="flex" title="Flex" path="@uxkm/vue/flex">
        <Flex gap="md">
          <span>Item A</span>
          <span>Item B</span>
          <span>Item C</span>
        </Flex>
      </DemoSection>

      <DemoSection id="grid" title="Grid" path="@uxkm/vue/grid">
        <Grid :cols="3" gap="md">
          <GridCol>Col 1</GridCol>
          <GridCol>Col 2</GridCol>
          <GridCol>Col 3</GridCol>
        </Grid>
      </DemoSection>

      <DemoSection id="space" title="Space" path="@uxkm/vue/space">
        <Space gap="md">
          <span>Space A</span>
          <span>Space B</span>
          <span>Space C</span>
        </Space>
      </DemoSection>

      <p>
        <NuxtLink class="link color_primary" to="/components">← 컴포넌트 목록</NuxtLink>
      </p>
    </div>
  </main>
</template>

<script setup>
import Container from '@uxkm/vue/container';
import Divider from '@uxkm/vue/divider';
import Flex from '@uxkm/vue/flex';
import Grid, { GridCol } from '@uxkm/vue/grid';
import Space from '@uxkm/vue/space';
import DemoSection from '../../components/demo/DemoSection.vue';
</script>
