// packages/ui-react/src/components/CalendarGroup.jsx
import { useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('CalendarGroup', { selfClosing: false });

export default function CalendarGroup({ children, className, ...rest }) {
  const rootRef = useRef(null);

  useComponentDemoCode(
    formatCode,
    {},
    createDemoSlots({ default: children }),
    rootRef,
    { className, ...rest },
  );

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  return (
    <div ref={rootRef} className={cn('calendar_group', className)} {...domRest}>
      {children}
    </div>
  );
}

// packages/ui/src/components/CalendarGroup.vue
<script setup>
import { ref } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const rootRef = ref(null);
const formatCode = createComponentFormatter('CalendarGroup', { selfClosing: false });

useComponentDemoCode(formatCode, {}, {}, rootRef, {});
</script>

<template>
  <div ref="rootRef" class="calendar_group">
    <slot />
  </div>
</template>
