// src/components/CardBody.jsx
import { useMemo, useRef } from 'react';
import { cn } from '@/utils/cn';
import { createComponentFormatter } from '@/utils/format-component-code';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';

const formatCode = createComponentFormatter('CardBody', { selfClosing: false });

export default function CardBody({ children, className, ...rest }) {
  const rootRef = useRef(null);
  const demoSlots = useMemo(() => createDemoSlots({ default: children }), [children]);

  useComponentDemoCode(formatCode, {}, demoSlots, rootRef, { class: className, ...rest });

  return (
    <div ref={rootRef} className={cn('card_body', className)} {...rest}>
      {children}
    </div>
  );
}

// packages/ui/src/components/CardBody.vue
<script setup>
import { ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({});
const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('CardBody', {
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);
</script>

<template>
  <div ref="rootRef" class="card_body" :class="attrs.class">
    <slot />
  </div>
</template>
