// packages/ui-react/src/components/Card.jsx
import { useMemo, useRef } from 'react';
import { useRipple } from '@/hooks/useRipple';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const VALID_VARIANTS = new Set(['bordered', 'shadow', 'flat']);
const VALID_SIZES = new Set(['sm', 'md', 'lg', 'compact']);

const formatCode = createComponentFormatter('Card', {
  defaults: { variant: 'bordered', size: 'md', tag: 'article' },
  booleanProps: new Set(['hoverable', 'ripple']),
  skipProps: ['tag'],
  selfClosing: false,
});

export default function Card({
  ripple,
  variant = 'bordered',
  size = 'md',
  hoverable,
  title,
  subtitle,
  tag = 'article',
  media,
  header,
  extra,
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const { rippleAttrs } = useRipple({ ripple }, { defaultEnabled: false });
  const resolvedVariant = VALID_VARIANTS.has(variant) ? variant : 'bordered';
  const resolvedSize = VALID_SIZES.has(size) ? size : 'md';

  useComponentDemoCode(
    formatCode,
    {
      ripple,
      variant: resolvedVariant,
      size: resolvedSize,
      hoverable,
      title,
      subtitle,
      tag,
    },
    createDemoSlots({ default: children, media, header, extra }),
    rootRef,
    { className, ...rest },
  );

  const rootClass = useMemo(() => {
    const classes = ['card'];
    if (resolvedVariant === 'shadow') classes.push('card_shadow');
    if (resolvedVariant === 'flat') classes.push('card_ghost');
    if (resolvedSize === 'sm') classes.push('card_sm');
    if (resolvedSize === 'lg') classes.push('card_lg');
    if (resolvedSize === 'compact') classes.push('card_compact');
    if (hoverable) classes.push('card_hover');
    return classes;
  }, [resolvedVariant, resolvedSize, hoverable]);

  const hasBuiltInHeader = Boolean(title || subtitle || header || extra);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);
  const Tag = tag || 'article';

  return (
    <Tag ref={rootRef} className={cn(rootClass, className)} {...rippleAttrs} {...domRest}>
      {media}
      {hasBuiltInHeader ? (
        <div className="card_header">
          <div className="card_header-main">
            {header ?? (
              <>
                {title ? <h3 className="card_title">{title}</h3> : null}
                {subtitle ? <p className="card_subtitle">{subtitle}</p> : null}
              </>
            )}
          </div>
          {extra ? <div className="card_extra">{extra}</div> : null}
        </div>
      ) : null}
      {children}
    </Tag>
  );
}

// packages/ui/src/components/Card.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  variant: {
    type: String,
    default: 'bordered',
    validator: (v) => ['bordered', 'shadow', 'flat'].includes(v),
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg', 'compact'].includes(v),
  },
  hoverable: Boolean,
  title: String,
  subtitle: String,
  tag: {
    type: String,
    default: 'article',
  },
});
const { rippleAttrs } = useRipple(props, { defaultEnabled: false });


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('Card', {
  defaults: { variant: 'bordered', size: 'md', tag: 'article' },
  booleanProps: new Set(['hoverable', 'ripple']),
  skipProps: ['tag'],
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['card'];
  if (props.variant === 'shadow') classes.push('card_shadow');
  if (props.variant === 'flat') classes.push('card_ghost');
  if (props.size === 'sm') classes.push('card_sm');
  if (props.size === 'lg') classes.push('card_lg');
  if (props.size === 'compact') classes.push('card_compact');
  if (props.hoverable) classes.push('card_hover');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const bindAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return { ...rest, ...rippleAttrs.value };
});

const hasBuiltInHeader = computed(
  () => Boolean(props.title || props.subtitle || slots.header || slots.extra)
);
</script>

<template>
  <component :is="tag" ref="rootRef" :class="rootClass" v-bind="bindAttrs">
    <slot name="media" />
    <div v-if="hasBuiltInHeader" class="card_header">
      <div class="card_header-main">
        <slot name="header">
          <h3 v-if="title" class="card_title">{{ title }}</h3>
          <p v-if="subtitle" class="card_subtitle">{{ subtitle }}</p>
        </slot>
      </div>
      <div v-if="$slots.extra" class="card_extra">
        <slot name="extra" />
      </div>
    </div>
    <slot />
  </component>
</template>
