// packages/ui-react/src/components/CategoryCard.jsx
import { useRipple } from '@/hooks/useRipple';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

export default function CategoryCard({
  ripple,
  title,
  description,
  count,
  href,
  target,
  className,
  ...rest
}) {
  const { rippleAttrs } = useRipple({ ripple });
  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  return (
    <a
      className={cn('category_card', className)}
      href={href}
      target={target}
      {...rippleAttrs}
      {...domRest}
    >
      <h3>{title}</h3>
      {description ? <p>{description}</p> : null}
      {count ? <span className="count">{count}</span> : null}
    </a>
  );
}

// packages/ui/src/components/CategoryCard.vue
<script setup>
import { rippleProp, useRipple } from '@/composables/useRipple';

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  title: {
    type: String,
    required: true,
  },
  description: String,
  count: String,
  href: {
    type: String,
    required: true,
  },
  target: String,
});

const { rippleAttrs } = useRipple(props);
</script>

<template>
  <a class="category_card" :href="href" :target="target" v-bind="rippleAttrs">
    <h3>{{ title }}</h3>
    <p v-if="description">{{ description }}</p>
    <span v-if="count" class="count">{{ count }}</span>
  </a>
</template>
