// src/components/DatePicker.jsx
import { useRef } from 'react';
import Button from '@/components/Button.jsx';
import Icon from '@/components/Icon.jsx';
import { cn } from '@/utils/cn';
import { rippleSurfaceAttrs, useRipple } from '@/hooks/useRipple';
import { useDatePickerDemoCode } from '@/hooks/useDemoCode';
import { normalizeDomProps } from '@/utils/normalize-dom-props';

export default function DatePicker({
  ripple,
  size = 'md',
  disabled,
  error,
  success,
  open,
  placeholder,
  value,
  fit,
  block,
  inline,
  clearable,
  panelWide,
  inputId,
  ariaLabel,
  ariaInvalid,
  ariaDescribedby,
  ariaDescribedBy,
  panel,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const props = {
    ripple,
    size,
    disabled,
    error,
    success,
    open,
    placeholder,
    value,
    fit,
    block,
    inline,
    clearable,
    panelWide,
    inputId,
    ariaLabel,
    ariaInvalid,
  };
  const { rippleAttrs, childRippleAttrs } = useRipple({ ripple }, { mode: 'container' });

  useDatePickerDemoCode(props, rootRef, { class: className, ...rest });

  const rootClass = cn(
    'date_picker',
    size === 'sm' && 'date_picker_sm',
    size === 'lg' && 'date_picker_lg',
    fit && 'date_picker_fit',
    block && 'date_picker_block',
    inline && 'date_picker_inline',
    disabled && 'is-disabled',
    error && 'is-error',
    success && 'is-success',
    open && 'is-open',
    className,
  );

  const inputClass = cn(
    'date_picker_input',
    !value && placeholder && 'date_picker_placeholder',
  );

  const showTrigger = !inline;
  const isExpanded = open;
  const hasValue = Boolean(value);

  const resolvedAriaInvalid =
    ariaInvalid === true || ariaInvalid === 'true'
      ? 'true'
      : ariaInvalid === false || ariaInvalid === 'false'
        ? 'false'
        : undefined;

  const domRest = normalizeDomProps(rest);
  const { style, 'aria-describedby': ariaDescribedByFromRest, ...inputDomRest } = domRest;
  const resolvedAriaDescribedBy =
    ariaDescribedBy ?? ariaDescribedby ?? ariaDescribedByFromRest;

  return (
    <div ref={rootRef} className={rootClass} style={style} {...rippleAttrs}>
      {showTrigger ? (
        <div className="date_picker_trigger">
          <input
            {...childRippleAttrs}
            {...inputDomRest}
            id={inputId}
            type="text"
            className={inputClass}
            value={value}
            placeholder={placeholder}
            readOnly
            disabled={disabled}
            aria-haspopup="dialog"
            aria-expanded={isExpanded ? 'true' : 'false'}
            aria-label={ariaLabel}
            aria-describedby={resolvedAriaDescribedBy}
            aria-invalid={resolvedAriaInvalid ?? inputDomRest['aria-invalid']}
          />
          {clearable && hasValue ? (
            <button
              type="button"
              className="date_picker_clear"
              aria-label="날짜 지우기"
              {...rippleSurfaceAttrs}
            >
              <Icon name="close" size="sm" />
            </button>
          ) : null}
          <Button
            {...childRippleAttrs}
            variant="ghost"
            iconOnly
            className="date_picker_btn"
            disabled={disabled}
            aria-label={isExpanded ? '캘린더 닫기' : '캘린더 열기'}
            expanded={isExpanded}
            iconBefore={<Icon name="calendar" size="sm" />}
          />
        </div>
      ) : null}
      {panel || inline ? (
        <div
          className={cn('date_picker_panel', panelWide && 'date_picker_panel-wide')}
          role="dialog"
          aria-label="날짜 선택"
          data-demo-slot="panel"
        >
          {panel}
        </div>
      ) : null}
    </div>
  );
}

// packages/ui/src/components/DatePicker.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import Button from '@/components/Button.vue';
import Icon from '@/components/Icon.vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useDatePickerDemoCode } from '@/composables/useDemoCode';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  disabled: Boolean,
  error: Boolean,
  success: Boolean,
  open: Boolean,
  placeholder: String,
  value: String,
  fit: Boolean,
  block: Boolean,
  inline: Boolean,
  clearable: Boolean,
  panelWide: Boolean,
  inputId: String,
  ariaLabel: String,
  ariaInvalid: [Boolean, String],
});
const { rippleAttrs, childRippleAttrs } = useRipple(props, { mode: 'container' });


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

useDatePickerDemoCode(props, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['date_picker'];
  if (props.size === 'sm') classes.push('date_picker_sm');
  if (props.size === 'lg') classes.push('date_picker_lg');
  if (props.fit) classes.push('date_picker_fit');
  if (props.block) classes.push('date_picker_block');
  if (props.inline) classes.push('date_picker_inline');
  if (props.disabled) classes.push('is-disabled');
  if (props.error) classes.push('is-error');
  if (props.success) classes.push('is-success');
  if (props.open) classes.push('is-open');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const inputClass = computed(() => {
  const classes = ['date_picker_input'];
  if (!props.value && props.placeholder) classes.push('date_picker_placeholder');
  return classes;
});

const showTrigger = computed(() => !props.inline);
const isExpanded = computed(() => props.open);
const hasValue = computed(() => Boolean(props.value));
</script>

<template>
  <div ref="rootRef" :class="rootClass"
    v-bind="rippleAttrs"
  >
    <div v-if="showTrigger" class="date_picker_trigger">
      <input
        v-bind="childRippleAttrs"
        :id="inputId"
        type="text"
        :class="inputClass"
        :value="value"
        :placeholder="placeholder"
        readonly
        :disabled="disabled"
        aria-haspopup="dialog"
        :aria-expanded="isExpanded ? 'true' : 'false'"
        :aria-label="ariaLabel"
        :aria-invalid="ariaInvalid === true || ariaInvalid === 'true' ? 'true' : ariaInvalid === false || ariaInvalid === 'false' ? 'false' : undefined"
      />
      <button
        v-if="clearable && hasValue"
        type="button"
        class="date_picker_clear"
        data-ripple="surface"
        aria-label="날짜 지우기"
      >
        <Icon name="close" size="sm" />
      </button>
      <Button
        v-bind="childRippleAttrs"
        variant="ghost"
        icon-only
        class="date_picker_btn"
        :disabled="disabled"
        :aria-label="isExpanded ? '캘린더 닫기' : '캘린더 열기'"
        :expanded="isExpanded"
      >
        <template #icon-before>
          <Icon name="calendar" size="sm" />
        </template>
      </Button>
    </div>
    <div
      v-if="$slots.panel || inline"
      class="date_picker_panel"
      :class="{ 'date_picker_panel-wide': panelWide }"
      role="dialog"
      aria-label="날짜 선택"
      data-demo-slot="panel"
    >
      <slot name="panel" />
    </div>
  </div>
</template>
