// packages/ui-react/src/components/Drawer.jsx
import { useMemo, useRef } from 'react';
import Button from '@/components/Button.jsx';
import Icon from '@/components/Icon.jsx';
import { useRipple } from '@/hooks/useRipple';
import { useDrawerDemoCode } from '@/hooks/useDemoCode';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const VALID_SIZES = new Set(['sm', 'md', 'lg']);
const VALID_PLACEMENTS = new Set(['left', 'right', 'top', 'bottom']);

const PLACEMENT_CLASS = {
  left: 'drawer_placement-left',
  right: 'drawer_placement-right',
  top: 'drawer_placement-top',
  bottom: 'drawer_placement-bottom',
};

export default function Drawer({
  ripple,
  id,
  size = 'md',
  placement = 'right',
  noBackdrop,
  openOnLoad,
  draggable,
  title,
  open,
  header,
  extra,
  footer,
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const { rippleAttrs } = useRipple({ ripple });
  const resolvedSize = VALID_SIZES.has(size) ? size : 'md';
  const resolvedPlacement = VALID_PLACEMENTS.has(placement) ? placement : 'right';
  const showDragHandle = Boolean(draggable && resolvedPlacement === 'bottom');
  const titleId = `${id}-title`;

  useDrawerDemoCode(
    {
      ripple,
      id,
      size: resolvedSize,
      placement: resolvedPlacement,
      noBackdrop,
      openOnLoad,
      draggable,
      title,
      open,
    },
    rootRef,
    { className, ...rest },
  );

  const panelClass = useMemo(() => {
    const classes = ['drawer_panel', PLACEMENT_CLASS[resolvedPlacement]];
    if (resolvedSize === 'sm') classes.push('drawer_sm');
    if (resolvedSize === 'lg') classes.push('drawer_lg');
    if (showDragHandle) classes.push('drawer_draggable');
    return classes;
  }, [resolvedPlacement, resolvedSize, showDragHandle]);

  const rootClass = useMemo(() => {
    const classes = ['drawer'];
    if (open) classes.push('is-open');
    return classes;
  }, [open]);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);
  const showHeader = Boolean(header || title);

  return (
    <div
      ref={rootRef}
      id={id}
      className={cn(rootClass, className)}
      data-drawer=""
      data-drawer-backdrop={noBackdrop ? 'false' : undefined}
      data-drawer-open-on-load={openOnLoad ? 'true' : undefined}
      data-drawer-draggable={showDragHandle ? 'true' : undefined}
      role="dialog"
      aria-modal="true"
      aria-labelledby={titleId}
      tabIndex={-1}
      hidden={!open || undefined}
      {...domRest}
    >
      <div className="drawer_backdrop" data-drawer-close="" aria-hidden="true" />
      <div className={cn(panelClass)}>
        {showDragHandle ? (
          <div
            className="drawer_handle"
            data-drawer-drag-handle=""
            role="presentation"
            aria-hidden="true"
          >
            <span className="drawer_handle-bar" />
          </div>
        ) : null}
        {showHeader ? (
          <div className="drawer_header" data-demo-slot="header">
            {header ?? (
              <h2 className="drawer_title" id={titleId}>
                {title}
              </h2>
            )}
            {extra ? (
              <div className="drawer_extra" data-demo-slot="extra">
                {extra}
              </div>
            ) : null}
            <Button
              variant="ghost"
              iconOnly
              className="drawer_close"
              data-drawer-close=""
              ariaLabel="닫기"
              iconBefore={<Icon name="close" size="sm" className="drawer_close-icon" />}
              {...rippleAttrs}
            />
          </div>
        ) : null}
        <div className="drawer_body" data-demo-slot="default">
          {children}
        </div>
        {footer ? (
          <div className="drawer_footer" data-demo-slot="footer">
            {footer}
          </div>
        ) : null}
      </div>
    </div>
  );
}

// packages/ui/src/components/Drawer.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import Button from '@/components/Button.vue';
import Icon from '@/components/Icon.vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useDrawerDemoCode } from '@/composables/useDemoCode';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  id: {
    type: String,
    required: true,
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  placement: {
    type: String,
    default: 'right',
    validator: (v) => ['left', 'right', 'top', 'bottom'].includes(v),
  },
  noBackdrop: Boolean,
  openOnLoad: Boolean,
  /** 하단 패널 핸들·헤더 드래그로 펼침/접힘 (placement="bottom") */
  draggable: Boolean,
  title: String,
  open: Boolean,
});
const { rippleAttrs } = useRipple(props);


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const titleId = `${props.id}-title`;
const showDragHandle = computed(() => props.draggable && props.placement === 'bottom');

useDrawerDemoCode(props, rootRef, attrs);

const placementClass = computed(() => {
  const map = {
    left: 'drawer_placement-left',
    right: 'drawer_placement-right',
    top: 'drawer_placement-top',
    bottom: 'drawer_placement-bottom',
  };
  return map[props.placement];
});

const panelClass = computed(() => {
  const classes = ['drawer_panel', placementClass.value];
  if (props.size === 'sm') classes.push('drawer_sm');
  if (props.size === 'lg') classes.push('drawer_lg');
  if (showDragHandle.value) classes.push('drawer_draggable');
  return classes;
});

const rootClass = computed(() => {
  const classes = ['drawer'];
  if (props.open) classes.push('is-open');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <div
    ref="rootRef"
    :id="id"
    :class="rootClass"
    data-drawer
    :data-drawer-backdrop="noBackdrop ? 'false' : undefined"
    :data-drawer-open-on-load="openOnLoad ? 'true' : undefined"
    :data-drawer-draggable="showDragHandle ? 'true' : undefined"
    role="dialog"
    aria-modal="true"
    :aria-labelledby="titleId"
    tabindex="-1"
    :hidden="!open || undefined"
    v-bind="fallthroughAttrs"
  >
    <div class="drawer_backdrop" data-drawer-close aria-hidden="true" />
    <div :class="panelClass">
      <div
        v-if="showDragHandle"
        class="drawer_handle"
        data-drawer-drag-handle
        role="presentation"
        aria-hidden="true"
      >
        <span class="drawer_handle-bar" />
      </div>
      <div v-if="$slots.header || title" class="drawer_header" data-demo-slot="header">
        <slot name="header">
          <h2 class="drawer_title" :id="titleId">{{ title }}</h2>
        </slot>
        <div v-if="$slots.extra" class="drawer_extra" data-demo-slot="extra">
          <slot name="extra" />
        </div>
        <Button
          variant="ghost"
          icon-only
          class="drawer_close"
          data-drawer-close
          aria-label="닫기"
          v-bind="rippleAttrs"
        >
          <template #icon-before>
            <Icon name="close" size="sm" class="drawer_close-icon" />
          </template>
        </Button>
      </div>
      <div class="drawer_body" data-demo-slot="default">
        <slot />
      </div>
      <div v-if="$slots.footer" class="drawer_footer" data-demo-slot="footer">
        <slot name="footer" />
      </div>
    </div>
  </div>
</template>
