// packages/ui-react/src/components/Table.jsx
import { useMemo, useRef } from 'react';
import { useTableDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { columnColStyle, columnRootVars } from '@/utils/table-column-sizing';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

export default function Table({
  bordered,
  striped,
  compact,
  hover,
  wrap = true,
  columns = [],
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const hasColumns = Array.isArray(columns) && columns.length > 0;

  useTableDemoCode(
    { bordered, striped, compact, hover, wrap, columns },
    createDemoSlots({ default: children }),
    rootRef,
    { className, ...rest },
  );

  const tableClass = useMemo(() => {
    const classes = ['table'];
    if (bordered) classes.push('table_bordered');
    if (striped) classes.push('table_striped');
    if (compact) classes.push('table_compact');
    if (hover) classes.push('table_hover');
    if (hasColumns) classes.push('table_columns');
    return classes;
  }, [bordered, striped, compact, hover, hasColumns]);

  const tableStyle = useMemo(() => columnRootVars(columns), [columns]);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  const colgroup = hasColumns ? (
    <colgroup>
      {columns.map((column, index) => (
        <col key={index} style={columnColStyle(column)} />
      ))}
    </colgroup>
  ) : null;

  if (wrap) {
    return (
      <div ref={rootRef} className={cn('table_wrap', className)} {...domRest}>
        <table className={cn(tableClass)} style={tableStyle}>
          {colgroup}
          {children}
        </table>
      </div>
    );
  }

  return (
    <table
      ref={rootRef}
      className={cn(tableClass, className)}
      style={tableStyle}
      {...domRest}
    >
      {colgroup}
      {children}
    </table>
  );
}

// packages/ui/src/components/Table.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useTableDemoCode } from '@/composables/useDemoCode';
import { columnColStyle, columnRootVars } from '@/utils/table-column-sizing';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  bordered: Boolean,
  striped: Boolean,
  compact: Boolean,
  hover: Boolean,
  wrap: {
    type: Boolean,
    default: true,
  },
  /** 열별 너비·패딩 — { width, minWidth, maxWidth, padding, nowrap } */
  columns: {
    type: Array,
    default: () => [],
  },
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

useTableDemoCode(props, slots, rootRef, attrs);

const hasColumns = computed(() => props.columns.length > 0);

const tableClass = computed(() => {
  const classes = ['table'];
  if (props.bordered) classes.push('table_bordered');
  if (props.striped) classes.push('table_striped');
  if (props.compact) classes.push('table_compact');
  if (props.hover) classes.push('table_hover');
  if (hasColumns.value) classes.push('table_columns');
  return classes;
});

const tableStyle = computed(() => columnRootVars(props.columns));

const wrapClass = computed(() => {
  const classes = ['table_wrap'];
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const colStyle = (column) => columnColStyle(column);
</script>

<template>
  <div v-if="wrap" ref="rootRef" :class="wrapClass">
    <table :class="tableClass" :style="tableStyle">
      <colgroup v-if="hasColumns">
        <col
          v-for="(column, index) in columns"
          :key="index"
          :style="colStyle(column)"
        />
      </colgroup>
      <slot />
    </table>
  </div>
  <table
    v-else
    ref="rootRef"
    :class="[...tableClass, attrs.class]"
    :style="tableStyle"
  >
    <colgroup v-if="hasColumns">
      <col
        v-for="(column, index) in columns"
        :key="index"
        :style="colStyle(column)"
      />
    </colgroup>
    <slot />
  </table>
</template>
