// src/components/BackTop.vue
<script setup>
import { computed, onMounted, ref, useAttrs, useSlots, watchEffect } from 'vue';
import Button from '@/components/Button.vue';
import Icon from '@/components/Icon.vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { initBackTop } from '@/legacy/back-top-init';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const VALID_SIZES = new Set(['sm', 'md', 'lg']);
const VALID_COLORS = new Set(['', 'primary', 'ghost']);

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  target: String,
  visibilityHeight: {
    type: [Number, String],
    default: 400,
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  color: {
    type: String,
    default: '',
    validator: (v) => ['', 'primary', 'ghost'].includes(v),
  },
  label: String,
  ariaLabel: {
    type: String,
    default: '맨 위로',
  },
  interactive: {
    type: Boolean,
    default: true,
  },
});
const { rippleAttrs } = useRipple(props);


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const mounted = ref(false);
const resolvedSize = computed(() =>
  VALID_SIZES.has(props.size) ? props.size : 'md'
);
const resolvedColor = computed(() =>
  VALID_COLORS.has(props.color) ? props.color : ''
);
const teleportDisabled = computed(() => Boolean(props.target) || !mounted.value);

const formatCode = createComponentFormatter('BackTop', {
  defaults: { visibilityHeight: 400, size: 'md', ariaLabel: '맨 위로', interactive: true },
  booleanProps: new Set(['interactive', 'ripple']),
  selfClosing: false,
});

useComponentDemoCode(
  formatCode,
  () => ({
    ...props,
    size: resolvedSize.value,
    color: resolvedColor.value || undefined,
  }),
  slots,
  rootRef,
  attrs
);

const rootClass = computed(() => {
  const classes = ['back_top'];
  if (resolvedSize.value === 'sm') classes.push('back_top_sm');
  if (resolvedSize.value === 'lg') classes.push('back_top_lg');
  if (resolvedColor.value === 'primary') classes.push('back_top_primary');
  if (resolvedColor.value === 'ghost') classes.push('back_top_ghost');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const rootAttrs = computed(() => {
  const result = {};
  if (props.interactive) result['data-back-top'] = '';
  if (props.target) result['data-target'] = props.target;
  if (Number(props.visibilityHeight) !== 400) {
    result['data-visibility-height'] = String(props.visibilityHeight);
  }
  return result;
});

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
const rootBindings = computed(() => ({
  ...rootAttrs.value,
  ...fallthroughAttrs.value,
}));

onMounted(() => {
  mounted.value = true;
});

watchEffect(
  (onCleanup) => {
    props.target;
    props.visibilityHeight;
    teleportDisabled.value;

    if (!props.interactive || !rootRef.value) return;
    onCleanup(initBackTop(rootRef.value));
  },
  { flush: 'post' }
);
</script>

<template>
  <Teleport to="body" :disabled="teleportDisabled">
    <div ref="rootRef" :class="rootClass" v-bind="rootBindings">
      <Button variant="ghost" class="back_top_btn" :aria-label="ariaLabel" v-bind="rippleAttrs">
        <slot>
          <Icon name="arrow-up" class="back_top_icon" />
          <span v-if="label" class="back_top_label">{{ label }}</span>
        </slot>
      </Button>
    </div>
  </Teleport>
</template>

// packages/ui-react/src/components/BackTop.jsx
import { useEffect, useMemo, useRef } from 'react';
import { createPortal } from 'react-dom';
import Button from '@/components/Button.jsx';
import Icon from '@/components/Icon.jsx';
import { initBackTop } from '@uxkm/ui/legacy/back-top-init.js';
import { useRipple } from '@/hooks/useRipple';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const VALID_SIZES = new Set(['sm', 'md', 'lg']);
const VALID_COLORS = new Set(['', 'primary', 'ghost']);

const formatCode = createComponentFormatter('BackTop', {
  defaults: { visibilityHeight: 400, size: 'md', ariaLabel: '맨 위로', interactive: true },
  booleanProps: new Set(['interactive', 'ripple']),
  selfClosing: false,
});

export default function BackTop({
  ripple,
  target,
  visibilityHeight = 400,
  size = 'md',
  color = '',
  label,
  ariaLabel = '맨 위로',
  interactive = true,
  children,
  className,
  style,
  ...rest
}) {
  const rootRef = useRef(null);
  const { rippleAttrs } = useRipple({ ripple });
  const resolvedSize = VALID_SIZES.has(size) ? size : 'md';
  const resolvedColor = VALID_COLORS.has(color) ? color : '';
  const teleported = !target;

  useComponentDemoCode(
    formatCode,
    {
      ripple,
      target,
      visibilityHeight,
      size: resolvedSize,
      color: resolvedColor || undefined,
      label,
      ariaLabel,
      interactive,
    },
    createDemoSlots({ default: children }),
    rootRef,
    { className, style, ...rest },
  );

  const rootClass = useMemo(() => {
    const classes = ['back_top'];
    if (resolvedSize === 'sm') classes.push('back_top_sm');
    if (resolvedSize === 'lg') classes.push('back_top_lg');
    if (resolvedColor === 'primary') classes.push('back_top_primary');
    if (resolvedColor === 'ghost') classes.push('back_top_ghost');
    return classes;
  }, [resolvedSize, resolvedColor]);

  const dataAttrs = useMemo(() => {
    const result = {};
    if (interactive) result['data-back-top'] = '';
    if (target) result['data-target'] = target;
    if (Number(visibilityHeight) !== 400) {
      result['data-visibility-height'] = String(visibilityHeight);
    }
    return result;
  }, [interactive, target, visibilityHeight]);

  useEffect(() => {
    if (!interactive || !rootRef.current) return undefined;
    return initBackTop(rootRef.current);
  }, [interactive, target, visibilityHeight]);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  const node = (
    <div
      ref={rootRef}
      className={cn(rootClass, className)}
      style={style}
      {...dataAttrs}
      {...domRest}
    >
      <Button variant="ghost" className="back_top_btn" ariaLabel={ariaLabel} {...rippleAttrs}>
        {children ?? (
          <>
            <Icon name="arrow-up" className="back_top_icon" />
            {label ? <span className="back_top_label">{label}</span> : null}
          </>
        )}
      </Button>
    </div>
  );

  if (teleported && typeof document !== 'undefined') {
    return createPortal(node, document.body);
  }

  return node;
}
