// packages/ui/src/components/SnackbarRegion.vue
<script setup>
import { computed, provide } from 'vue';

const props = defineProps({
  placement: {
    type: String,
    default: 'bottom-center',
    validator: (value) => [
      'top-start', 'top-center', 'top-end',
      'middle-start', 'middle-end',
      'bottom-start', 'bottom-center', 'bottom-end',
    ].includes(value),
  },
  label: String,
});

const placement = computed(() => props.placement);
provide('uxkm-snackbar-placement', placement);
</script>

<template>
  <Teleport to="body">
    <div
      class="snackbar_region"
      :class="`snackbar_region-${placement}`"
      :role="label ? 'region' : undefined"
      :aria-label="label"
    >
      <slot />
    </div>
  </Teleport>
</template>

// packages/ui-react/src/components/SnackbarRegion.jsx
import { createContext } from 'react';
import { createPortal } from 'react-dom';
import { cn } from '@/utils/cn';
import { normalizeDomProps } from '@/utils/normalize-dom-props';

export const SnackbarPlacementContext = createContext('bottom-center');

export const SNACKBAR_PLACEMENTS = [
  'top-start',
  'top-center',
  'top-end',
  'middle-start',
  'middle-end',
  'bottom-start',
  'bottom-center',
  'bottom-end',
];

const VALID_PLACEMENTS = new Set(SNACKBAR_PLACEMENTS);

export default function SnackbarRegion({
  placement = 'bottom-center',
  label,
  children,
  className,
  ...rest
}) {
  const resolvedPlacement = VALID_PLACEMENTS.has(placement)
    ? placement
    : 'bottom-center';
  const domRest = normalizeDomProps(rest);

  const node = (
    <SnackbarPlacementContext.Provider value={resolvedPlacement}>
      <div
        className={cn(
          'snackbar_region',
          `snackbar_region-${resolvedPlacement}`,
          className,
        )}
        aria-label={label}
        {...domRest}
      >
        {children}
      </div>
    </SnackbarPlacementContext.Provider>
  );

  if (typeof document !== 'undefined') {
    return createPortal(node, document.body);
  }

  return node;
}
