// src/components/TypoText.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const VARIANT_MAP = {
  paragraph: { tag: 'p', class: 'typo_paragraph' },
  lead: { tag: 'p', class: 'typo_lead' },
  caption: { tag: 'p', class: 'typo_caption' },
  label: { tag: 'label', class: 'typo_label' },
  overline: { tag: 'p', class: 'typo_overline' },
  code: { tag: 'code', class: 'typo_code' },
  kbd: { tag: 'kbd', class: 'typo_kbd' },
  pre: { tag: 'pre', class: 'typo_pre' },
  strong: { tag: 'span', class: 'typo_strong' },
  italic: { tag: 'span', class: 'typo_italic' },
  underline: { tag: 'span', class: 'typo_underline' },
  delete: { tag: 'span', class: 'typo_delete' },
  mark: { tag: 'span', class: 'typo_mark' },
  sub: { tag: 'sub', class: 'typo_sub' },
  sup: { tag: 'sup', class: 'typo_sup' },
  small: { tag: 'small', class: 'typo_small' },
  link: { tag: 'a', class: 'typo_link' },
  blockquote: { tag: 'blockquote', class: 'typo_blockquote' },
  text: { tag: 'p', class: '' },
};

const props = defineProps({
  variant: {
    type: String,
    default: 'text',
  },
  color: String,
  size: {
    type: String,
    default: '',
    validator: (v) => ['', 'xs', 'sm', 'lg', 'xl'].includes(v),
  },
  ellipsis: {
    type: [Number, String],
    default: undefined,
    validator: (v) => v == null || [0, 1, 2, 3, '0', '1', '2', '3'].includes(v),
  },
  href: String,
  htmlFor: String,
  cite: String,
  label: String,
  tag: String,
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('TypoText', {
  defaults: { variant: 'text', ellipsis: 0 },
  skipProps: ['tag'],
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const variantConfig = computed(() => VARIANT_MAP[props.variant] || VARIANT_MAP.text);

const rootTag = computed(() => props.tag || variantConfig.value.tag);

const ellipsisLines = computed(() => {
  if (props.ellipsis == null || props.ellipsis === '') return 0;
  const lines = Number(props.ellipsis);
  return lines >= 1 && lines <= 3 ? lines : 0;
});

const rootClass = computed(() => {
  const classes = [];
  if (variantConfig.value.class) classes.push(variantConfig.value.class);
  if (props.color) classes.push(`color_${props.color}`);
  if (props.size === 'xs') classes.push('size_xs');
  if (props.size === 'sm') classes.push('size_sm');
  if (props.size === 'lg') classes.push('size_lg');
  if (props.size === 'xl') classes.push('size_xl');
  if (ellipsisLines.value === 1) classes.push('text_ellipsis');
  if (ellipsisLines.value === 2) classes.push('text_ellipsis-2');
  if (ellipsisLines.value === 3) classes.push('text_ellipsis-3');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});
</script>

<template>
  <component
    :is="rootTag"
    ref="rootRef"
    :class="rootClass"
    :href="variant === 'link' ? (href || '#') : undefined"
    :for="variant === 'label' ? htmlFor : undefined"
    :cite="variant === 'blockquote' ? cite : undefined"
    @click="variant === 'link' && !href ? $event.preventDefault() : undefined"
  >
    <slot>{{ label }}</slot>
  </component>
</template>

// packages/ui-react/src/components/TypoText.jsx
import { useMemo, useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const VARIANT_MAP = {
  paragraph: { tag: 'p', className: 'typo_paragraph' },
  lead: { tag: 'p', className: 'typo_lead' },
  caption: { tag: 'p', className: 'typo_caption' },
  label: { tag: 'label', className: 'typo_label' },
  overline: { tag: 'p', className: 'typo_overline' },
  code: { tag: 'code', className: 'typo_code' },
  kbd: { tag: 'kbd', className: 'typo_kbd' },
  pre: { tag: 'pre', className: 'typo_pre' },
  strong: { tag: 'span', className: 'typo_strong' },
  italic: { tag: 'span', className: 'typo_italic' },
  underline: { tag: 'span', className: 'typo_underline' },
  delete: { tag: 'span', className: 'typo_delete' },
  mark: { tag: 'span', className: 'typo_mark' },
  sub: { tag: 'sub', className: 'typo_sub' },
  sup: { tag: 'sup', className: 'typo_sup' },
  small: { tag: 'small', className: 'typo_small' },
  link: { tag: 'a', className: 'typo_link' },
  blockquote: { tag: 'blockquote', className: 'typo_blockquote' },
  text: { tag: 'p', className: '' },
};

const VALID_SIZES = new Set(['', 'xs', 'sm', 'lg', 'xl']);

const formatCode = createComponentFormatter('TypoText', {
  defaults: { variant: 'text', ellipsis: 0 },
  skipProps: ['tag'],
  selfClosing: false,
});

export default function TypoText({
  variant = 'text',
  color,
  size = '',
  ellipsis,
  href,
  htmlFor,
  cite,
  label,
  tag,
  children,
  className,
  onClick,
  ...rest
}) {
  const rootRef = useRef(null);
  const variantConfig = VARIANT_MAP[variant] || VARIANT_MAP.text;
  const resolvedSize = VALID_SIZES.has(size) ? size : '';
  const content = children ?? label;

  useComponentDemoCode(
    formatCode,
    {
      variant,
      color,
      size: resolvedSize,
      ellipsis,
      href,
      htmlFor,
      cite,
      label,
    },
    createDemoSlots({ default: content }),
    rootRef,
    { className, onClick, ...rest },
  );

  const ellipsisLines = useMemo(() => {
    if (ellipsis == null || ellipsis === '') return 0;
    const lines = Number(ellipsis);
    return lines >= 1 && lines <= 3 ? lines : 0;
  }, [ellipsis]);

  const rootClass = useMemo(() => {
    const classes = [];
    if (variantConfig.className) classes.push(variantConfig.className);
    if (color) classes.push(`color_${color}`);
    if (resolvedSize === 'xs') classes.push('size_xs');
    if (resolvedSize === 'sm') classes.push('size_sm');
    if (resolvedSize === 'lg') classes.push('size_lg');
    if (resolvedSize === 'xl') classes.push('size_xl');
    if (ellipsisLines === 1) classes.push('text_ellipsis');
    if (ellipsisLines === 2) classes.push('text_ellipsis-2');
    if (ellipsisLines === 3) classes.push('text_ellipsis-3');
    return classes;
  }, [variantConfig.className, color, resolvedSize, ellipsisLines]);

  const Tag = tag || variantConfig.tag;
  const domRest = normalizeDomProps(rest);

  function handleClick(event) {
    if (variant === 'link' && !href) {
      event.preventDefault();
    }
    onClick?.(event);
  }

  return (
    <Tag
      ref={rootRef}
      className={cn(rootClass, className)}
      href={variant === 'link' ? href || '#' : undefined}
      htmlFor={variant === 'label' ? htmlFor : undefined}
      cite={variant === 'blockquote' ? cite : undefined}
      onClick={variant === 'link' ? handleClick : onClick}
      {...domRest}
    >
      {content}
    </Tag>
  );
}
