// apps/angular/src/components/data-display/List/list-item.component.ts
import { Component, computed, contentChildren, inject, input } from '@angular/core';
import { LIST_CONTEXT } from './list.component';

@Component({
  selector: 'ListItem',
  standalone: true,
  template: `
    @if (definitionPair()) {
      <dt [class]="titleClasses()" data-component="ListItem">{{ title() }}</dt>
      <dd class="list_desc">{{ description() }}</dd>
    } @else {
      @switch (rootTag()) {
        @case ('dt') {
          <dt [class]="itemClasses()" data-component="ListItem" [attr.role]="itemRole() ?? null">
            <ng-content select="[prefix]" />
            @if (hasContent()) {
              <div class="list_content">
                <ng-content>
                  @if (title()) { <span class="list_title">{{ title() }}</span> }
                  @if (meta()) { <span class="list_meta">{{ meta() }}</span> }
                  @if (description()) { <span class="list_desc">{{ description() }}</span> }
                </ng-content>
              </div>
            }
            @if (hasExtra()) { <span class="list_extra"><ng-content select="[extra]" /></span> }
            @if (hasActions()) { <span class="list_action"><ng-content select="[actions]" /></span> }
          </dt>
        }
        @case ('dd') {
          <dd [class]="itemClasses()" data-component="ListItem" [attr.role]="itemRole() ?? null">
            <ng-content select="[prefix]" />
            @if (hasContent()) {
              <div class="list_content">
                <ng-content>
                  @if (title()) { <span class="list_title">{{ title() }}</span> }
                  @if (meta()) { <span class="list_meta">{{ meta() }}</span> }
                  @if (description()) { <span class="list_desc">{{ description() }}</span> }
                </ng-content>
              </div>
            }
            @if (hasExtra()) { <span class="list_extra"><ng-content select="[extra]" /></span> }
            @if (hasActions()) { <span class="list_action"><ng-content select="[actions]" /></span> }
          </dd>
        }
        @case ('div') {
          <div [class]="itemClasses()" data-component="ListItem" role="listitem">
            <ng-content select="[prefix]" />
            @if (hasContent()) {
              <div class="list_content">
                <ng-content>
                  @if (title()) { <span class="list_title">{{ title() }}</span> }
                  @if (meta()) { <span class="list_meta">{{ meta() }}</span> }
                  @if (description()) { <span class="list_desc">{{ description() }}</span> }
                </ng-content>
              </div>
            }
            @if (hasExtra()) { <span class="list_extra"><ng-content select="[extra]" /></span> }
            @if (hasActions()) { <span class="list_action"><ng-content select="[actions]" /></span> }
          </div>
        }
        @default {
          <li [class]="itemClasses()" data-component="ListItem" [attr.role]="itemRole() ?? null">
            <ng-content select="[prefix]" />
            @if (hasContent()) {
              <div class="list_content">
                <ng-content>
                  @if (title()) { <span class="list_title">{{ title() }}</span> }
                  @if (meta()) { <span class="list_meta">{{ meta() }}</span> }
                  @if (description()) { <span class="list_desc">{{ description() }}</span> }
                </ng-content>
              </div>
            }
            @if (hasExtra()) { <span class="list_extra"><ng-content select="[extra]" /></span> }
            @if (hasActions()) { <span class="list_action"><ng-content select="[actions]" /></span> }
          </li>
        }
      }
    }
  `,
})
export class ListItem {
  readonly hostClass = input<string>('');
  readonly title = input<string | undefined>(undefined);
  readonly description = input<string | undefined>(undefined);
  readonly meta = input<string | undefined>(undefined);
  readonly tag = input<string>('auto');
  readonly role = input<string | undefined>(undefined);

  private readonly context = inject(LIST_CONTEXT, { optional: true });
  private readonly projected = contentChildren('*');
  private readonly prefixProjected = contentChildren('[prefix]');
  private readonly extraProjected = contentChildren('[extra]');
  private readonly actionsProjected = contentChildren('[actions]');

  readonly definitionPair = computed(
    () =>
      this.tag() === 'auto' &&
      this.context?.tag() === 'dl' &&
      Boolean(this.title() && this.description()),
  );

  readonly rootTag = computed(() => {
    const itemTag = this.tag();
    if (itemTag !== 'auto' && ['li', 'dt', 'dd'].includes(itemTag)) return itemTag;
    const parentTag = this.context?.tag() ?? 'ul';
    if (this.tag() === 'auto' && parentTag === 'dl') return this.title() ? 'dt' : 'dd';
    if (this.tag() === 'auto' && parentTag === 'div') return 'div';
    return 'li';
  });

  readonly hasContent = computed(() =>
    Boolean(
      this.title() ||
        this.description() ||
        this.meta() ||
        this.projected().length > 0,
    ),
  );

  readonly hasExtra = computed(() => this.extraProjected().length > 0);
  readonly hasActions = computed(() => this.actionsProjected().length > 0);

  readonly itemRole = computed(() =>
    this.role() ?? (this.context?.tag() === 'div' ? 'listitem' : undefined),
  );

  readonly titleClasses = computed(() =>
    ['list_title', this.hostClass()].filter(Boolean).join(' '),
  );

  readonly itemClasses = computed(() =>
    ['list_item', this.hostClass()].filter(Boolean).join(' '),
  );
}

export default ListItem;

// apps/vue/src/components/data-display/List/ListItem.vue
<script setup>
import { computed, inject, useAttrs, useSlots } from 'vue';

defineOptions({ name: 'UxkmListItem', inheritAttrs: false });
const props = defineProps({
  title: String, description: String, meta: String,
  tag: { type: String, default: 'auto', validator: (value) => ['auto', 'li', 'dt', 'dd'].includes(value) }
});
const attrs = useAttrs();
const slots = useSlots();
const context = inject('uxkmListContext', computed(() => ({ tag: 'ul', variant: 'default' })));
const definitionPair = computed(() => props.tag === 'auto' && context.value.tag === 'dl' && Boolean(props.title && props.description));
const rootTag = computed(() => {
  if (props.tag !== 'auto') return props.tag;
  if (context.value.tag === 'dl') return props.title ? 'dt' : 'dd';
  if (context.value.tag === 'div') return 'div';
  return 'li';
});
const hasContent = computed(() => Boolean(props.title || props.description || props.meta || slots.default));
const fallthroughAttrs = computed(() => { const { class: _class, role: _role, ...rest } = attrs; return rest; });
</script>

<template>
  <template v-if="definitionPair">
    <dt v-bind="fallthroughAttrs" class="list_title" :class="attrs.class">{{ title }}</dt>
    <dd class="list_desc">{{ description }}</dd>
  </template>
  <component v-else :is="rootTag" v-bind="fallthroughAttrs" class="list_item" :class="attrs.class" data-component="ListItem" :role="attrs.role ?? (context.tag === 'div' ? 'listitem' : undefined)">
    <slot name="prefix" />
    <div v-if="hasContent" class="list_content"><slot><span v-if="title" class="list_title">{{ title }}</span><span v-if="meta" class="list_meta">{{ meta }}</span><span v-if="description" class="list_desc">{{ description }}</span></slot></div>
    <span v-if="$slots.extra" class="list_extra"><slot name="extra" /></span>
    <span v-if="$slots.actions" class="list_action"><slot name="actions" /></span>
  </component>
</template>
