// packages/ui/src/components/Avatar.vue
<script setup>
import { computed, ref, useAttrs, useSlots, watch } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false, name: 'Avatar' });

const props = defineProps({
  src: String,
  alt: String,
  initials: String,
  color: String,
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg', 'xl'].includes(v),
  },
  square: Boolean,
  badgeColor: String,
  badgeLabel: String,
  ariaHidden: Boolean,
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const imageError = ref(false);

const formatCode = createComponentFormatter('Avatar', {
  defaults: { size: 'md' },
  booleanProps: new Set(['square', 'ariaHidden']),
  skipProps: ['badgeColor', 'badgeLabel'],
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['avatar'];
  if (props.color) classes.push(`color_${props.color}`);
  if (props.size === 'sm') classes.push('avatar_sm');
  if (props.size === 'lg') classes.push('avatar_lg');
  if (props.size === 'xl') classes.push('avatar_xl');
  if (props.square) classes.push('avatar_square');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const showImage = computed(() => Boolean(props.src) && !imageError.value);

watch(
  () => props.src,
  () => {
    imageError.value = false;
  }
);

const showInitials = computed(
  () => !showImage.value && !slots.icon && props.initials
);
</script>

<template>
  <span
    ref="rootRef"
    :class="rootClass"
    :aria-hidden="ariaHidden ? 'true' : undefined"
  >
    <img
      v-if="showImage"
      class="avatar_image"
      :src="src"
      :alt="alt || ''"
      @error="imageError = true"
    />
    <slot v-else-if="$slots.icon" name="icon" />
    <template v-else-if="showInitials">{{ initials }}</template>
    <span
      v-if="badgeColor"
      class="avatar_badge"
      :class="`color_${badgeColor}`"
      :aria-label="badgeLabel"
    />
  </span>
</template>

// src/components/Avatar.jsx
import { useMemo, useRef } from 'react';
import { cn } from '@/utils/cn';
import { createComponentFormatter } from '@/utils/format-component-code';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';

const formatCode = createComponentFormatter('Avatar', {
  defaults: { size: 'md' },
  booleanProps: new Set(['square', 'ariaHidden']),
  skipProps: ['badgeColor', 'badgeLabel'],
});

export default function Avatar({
  src,
  alt,
  initials,
  color,
  size = 'md',
  square,
  badgeColor,
  badgeLabel,
  ariaHidden,
  icon,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const props = { src, alt, initials, color, size, square, badgeColor, badgeLabel, ariaHidden };
  const demoSlots = useMemo(() => createDemoSlots({ icon }), [icon]);

  useComponentDemoCode(formatCode, props, demoSlots, rootRef, { class: className, ...rest });

  const rootClass = cn(
    'avatar',
    color && `color_${color}`,
    size === 'sm' && 'avatar_sm',
    size === 'lg' && 'avatar_lg',
    size === 'xl' && 'avatar_xl',
    square && 'avatar_square',
    className,
  );

  const showInitials = !src && !icon && initials;

  return (
    <span ref={rootRef} className={rootClass} aria-hidden={ariaHidden ? 'true' : undefined} {...rest}>
      {src ? (
        <img className="avatar_image" src={src} alt={alt || ''} />
      ) : icon ? (
        icon
      ) : showInitials ? (
        initials
      ) : null}
      {badgeColor ? (
        <span
          className={cn('avatar_badge', `color_${badgeColor}`)}
          aria-label={badgeLabel}
        />
      ) : null}
    </span>
  );
}
