// packages/ui-react/src/components/BadgeWrap.jsx
import { useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('BadgeWrap', { selfClosing: false });

export default function BadgeWrap({ ariaLabel, children, className, ...rest }) {
  const rootRef = useRef(null);

  useComponentDemoCode(
    formatCode,
    { ariaLabel },
    createDemoSlots({ default: children }),
    rootRef,
    { className, ...rest },
  );

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  return (
    <span ref={rootRef} className={cn('badge_wrap', className)} aria-label={ariaLabel} {...domRest}>
      {children}
    </span>
  );
}

// src/components/BadgeWrap.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  ariaLabel: String,
});

const rootRef = ref(null);
const attrs = useAttrs();
const slots = useSlots();
const formatCode = createComponentFormatter('BadgeWrap', { selfClosing: false });

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => ['badge_wrap', attrs.class].filter(Boolean));
const fallthroughAttrs = computed(() => {
  const { class: _class, 'aria-label': _ariaLabel, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <span
    ref="rootRef"
    v-bind="fallthroughAttrs"
    :class="rootClass"
    :aria-label="ariaLabel ?? attrs['aria-label']"
  >
    <slot />
  </span>
</template>
