// src/components/CalendarMonth.vue
<script setup>
import CalendarDay from '@/components/CalendarDay.vue';
import CalendarGrid from '@/components/CalendarGrid.vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { june2024Days, partialMonthDays } from '@/data/calendar-demo';
import { formatCalendarMonthCode } from '@/utils/format-calendar-month-code';
import { computed, ref } from 'vue';

const props = defineProps({
  days: Array,
  preset: {
    type: String,
    default: '',
  },
  selected: Number,
  today: Number,
  disabled: Array,
  events: Array,
  rangeStart: Number,
  rangeEnd: Number,
  weekends: Boolean,
  partial: Number,
  week: Boolean,
  readonly: Boolean,
});

const rootRef = ref(null);

useComponentDemoCode(
  (monthProps, _slots, monthAttrs) => formatCalendarMonthCode(monthProps, monthAttrs),
  props,
  {},
  rootRef,
  {},
);

const resolvedDays = computed(() => {
  if (props.days?.length) return props.days;

  if (props.partial) {
    return partialMonthDays(props.partial, {
      today: props.today,
      selected: props.selected,
    });
  }

  if (props.preset === 'june2024' || !props.preset) {
    return june2024Days({
      selected: props.selected,
      today: props.today,
      disabled: props.disabled,
      events: props.events,
      rangeStart: props.rangeStart,
      rangeEnd: props.rangeEnd,
    });
  }

  return [];
});

const displayDays = computed(() => {
  const days = resolvedDays.value;
  if (!props.weekends) return days;
  return days.map((cell, index) => ({
    ...cell,
    sunday: cell.sunday ?? index % 7 === 0,
    saturday: cell.saturday ?? index % 7 === 6,
  }));
});
</script>

<template>
  <div ref="rootRef" class="calendar_month" style="display: contents">
    <CalendarGrid :week="week">
      <CalendarDay
        v-for="(cell, index) in displayDays"
        :key="`${cell.day}-${index}`"
        v-bind="cell"
        :readonly="readonly"
      />
    </CalendarGrid>
  </div>
</template>

// src/components/CalendarMonth.jsx
import { useMemo, useRef } from 'react';
import CalendarDay from '@/components/CalendarDay.jsx';
import CalendarGrid from '@/components/CalendarGrid.jsx';
import { useComponentDemoCode } from '@/hooks/useDemoCode';
import { june2024Days, partialMonthDays } from '@/data/calendar-demo';
import { formatCalendarMonthCode } from '@/utils/format-calendar-month-code';

export default function CalendarMonth({
  days,
  preset = '',
  selected,
  today,
  disabled,
  events,
  rangeStart,
  rangeEnd,
  weekends,
  partial,
  week,
  readonly,
}) {
  const rootRef = useRef(null);

  useComponentDemoCode(
    (monthProps, _slots, monthAttrs) => formatCalendarMonthCode(monthProps, monthAttrs),
    { days, preset, selected, today, disabled, events, rangeStart, rangeEnd, weekends, partial, week, readonly },
    {},
    rootRef,
    {},
  );

  const resolvedDays = useMemo(() => {
    if (days?.length) return days;

    if (partial) {
      return partialMonthDays(partial, { today, selected });
    }

    if (preset === 'june2024' || !preset) {
      return june2024Days({ selected, today, disabled, events, rangeStart, rangeEnd });
    }

    return [];
  }, [days, partial, preset, selected, today, disabled, events, rangeStart, rangeEnd]);

  const displayDays = useMemo(() => {
    if (!weekends) return resolvedDays;
    return resolvedDays.map((cell, index) => ({
      ...cell,
      sunday: cell.sunday ?? index % 7 === 0,
      saturday: cell.saturday ?? index % 7 === 6,
    }));
  }, [resolvedDays, weekends]);

  return (
    <div ref={rootRef} className="calendar_month" style={{ display: 'contents' }}>
      <CalendarGrid week={week}>
        {displayDays.map((cell, index) => (
          <CalendarDay key={`${cell.day}-${index}`} {...cell} readonly={readonly} />
        ))}
      </CalendarGrid>
    </div>
  );
}
