// packages/ui/src/components/CalendarGroup.vue
<script setup>
import { ref } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const rootRef = ref(null);
const formatCode = createComponentFormatter('CalendarGroup', { selfClosing: false });

useComponentDemoCode(formatCode, {}, {}, rootRef, {});
</script>

<template>
  <div ref="rootRef" class="calendar_group">
    <slot />
  </div>
</template>

// src/components/CalendarGroup.jsx
import { useRef } from 'react';
import { useComponentDemoCode } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const formatCode = createComponentFormatter('CalendarGroup', { selfClosing: false });

export default function CalendarGroup({ children }) {
  const rootRef = useRef(null);

  useComponentDemoCode(formatCode, {}, { default: () => children }, rootRef, {});

  return (
    <div ref={rootRef} className="calendar_group">
      {children}
    </div>
  );
}
