// packages/ui-react/src/components/CardHeader.jsx
import { useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('CardHeader', {
  selfClosing: false,
});

export default function CardHeader({
  title,
  subtitle,
  extra,
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);

  useComponentDemoCode(
    formatCode,
    { title, subtitle },
    createDemoSlots({ default: children, extra }),
    rootRef,
    { className, ...rest },
  );

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  return (
    <div ref={rootRef} className={cn('card_header', className)} {...domRest}>
      <div className="card_header-main">
        {children ?? (
          <>
            {title ? <h3 className="card_title">{title}</h3> : null}
            {subtitle ? <p className="card_subtitle">{subtitle}</p> : null}
          </>
        )}
      </div>
      {extra ? <div className="card_extra">{extra}</div> : null}
    </div>
  );
}

// src/components/CardHeader.vue
<script setup>
import { ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  title: String,
  subtitle: String,
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('CardHeader', {
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);
</script>

<template>
  <div ref="rootRef" class="card_header" :class="attrs.class">
    <div class="card_header-main">
      <slot>
        <h3 v-if="title" class="card_title">{{ title }}</h3>
        <p v-if="subtitle" class="card_subtitle">{{ subtitle }}</p>
      </slot>
    </div>
    <div v-if="$slots.extra" class="card_extra">
      <slot name="extra" />
    </div>
  </div>
</template>
