// src/components/FormLayout.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const VALID_LAYOUTS = new Set(['vertical', 'horizontal', 'inline', '']);
const VALID_LABEL_WIDTHS = new Set(['', 'sm', 'lg']);

defineOptions({ inheritAttrs: false });

const props = defineProps({
  layout: {
    type: String,
    default: 'vertical',
    validator: (v) => ['vertical', 'horizontal', 'inline', ''].includes(v),
  },
  fit: Boolean,
  compact: Boolean,
  labelAlignStart: Boolean,
  labelWidth: {
    type: String,
    default: '',
    validator: (v) => ['', 'sm', 'lg'].includes(v),
  },
  tag: {
    type: String,
    default: 'form',
  },
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const resolvedLayout = computed(() =>
  VALID_LAYOUTS.has(props.layout) ? props.layout : 'vertical'
);
const resolvedLabelWidth = computed(() =>
  VALID_LABEL_WIDTHS.has(props.labelWidth) ? props.labelWidth : ''
);
const resolvedTag = computed(() => props.tag || 'form');

const formatCode = createComponentFormatter('FormLayout', {
  defaults: { layout: 'vertical', tag: 'form' },
  booleanProps: new Set(['fit', 'compact', 'labelAlignStart']),
  skipProps: ['tag'],
  selfClosing: false,
});

useComponentDemoCode(
  formatCode,
  () => ({
    ...props,
    layout: resolvedLayout.value,
    labelWidth: resolvedLabelWidth.value,
    tag: resolvedTag.value,
  }),
  slots,
  rootRef,
  attrs
);

const rootClass = computed(() => {
  const classes = ['form'];
  if (resolvedLayout.value === 'vertical') classes.push('form_vertical');
  if (resolvedLayout.value === 'horizontal') classes.push('form_horizontal');
  if (resolvedLayout.value === 'inline') classes.push('form_inline');
  if (props.fit) classes.push('form_fit');
  if (props.compact) classes.push('form_compact');
  if (props.labelAlignStart) classes.push('form_label-align-start');
  if (resolvedLabelWidth.value === 'sm') classes.push('form_label-width-sm');
  if (resolvedLabelWidth.value === 'lg') classes.push('form_label-width-lg');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <component :is="resolvedTag" ref="rootRef" :class="rootClass" v-bind="fallthroughAttrs">
    <slot />
  </component>
</template>

// src/components/FormLayout.jsx
import { useMemo, useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const VALID_LAYOUTS = new Set(['vertical', 'horizontal', 'inline', '']);
const VALID_LABEL_WIDTHS = new Set(['', 'sm', 'lg']);

const formatCode = createComponentFormatter('FormLayout', {
  defaults: { layout: 'vertical', tag: 'form' },
  booleanProps: new Set(['fit', 'compact', 'labelAlignStart']),
  skipProps: ['tag'],
  selfClosing: false,
});

export default function FormLayout({
  layout = 'vertical',
  fit,
  compact,
  labelAlignStart,
  labelWidth = '',
  tag = 'form',
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const resolvedLayout = VALID_LAYOUTS.has(layout) ? layout : 'vertical';
  const resolvedLabelWidth = VALID_LABEL_WIDTHS.has(labelWidth) ? labelWidth : '';

  useComponentDemoCode(
    formatCode,
    {
      layout: resolvedLayout,
      fit,
      compact,
      labelAlignStart,
      labelWidth: resolvedLabelWidth,
      tag,
    },
    createDemoSlots({ default: children }),
    rootRef,
    { className, ...rest },
  );

  const rootClass = useMemo(() => {
    const classes = ['form'];
    if (resolvedLayout === 'vertical') classes.push('form_vertical');
    if (resolvedLayout === 'horizontal') classes.push('form_horizontal');
    if (resolvedLayout === 'inline') classes.push('form_inline');
    if (fit) classes.push('form_fit');
    if (compact) classes.push('form_compact');
    if (labelAlignStart) classes.push('form_label-align-start');
    if (resolvedLabelWidth === 'sm') classes.push('form_label-width-sm');
    if (resolvedLabelWidth === 'lg') classes.push('form_label-width-lg');
    return classes;
  }, [resolvedLayout, fit, compact, labelAlignStart, resolvedLabelWidth]);

  const Tag = tag || 'form';
  const domRest = normalizeDomProps(rest);

  return (
    <Tag ref={rootRef} className={cn(rootClass, className)} {...domRest}>
      {children}
    </Tag>
  );
}
