// src/components/GridCol.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  as: {
    type: String,
    default: 'div',
  },
  span: [Number, String],
  spanMd: [Number, String],
  spanLg: [Number, String],
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('GridCol', {
  defaults: { as: 'div' },
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = [];
  if (props.span != null) classes.push(`grid_col-span-${props.span}`);
  if (props.spanMd != null) classes.push(`grid_col-span-md-${props.spanMd}`);
  if (props.spanLg != null) classes.push(`grid_col-span-lg-${props.spanLg}`);
  return classes;
});
</script>

<template>
  <component :is="props.as" ref="rootRef" v-bind="attrs" :class="rootClass">
    <slot />
  </component>
</template>

// src/components/GridCol.jsx
import { useMemo, useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('GridCol', {
  selfClosing: false,
});

export default function GridCol({
  as: Component = 'div',
  span,
  spanMd,
  spanLg,
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const demoSlots = useMemo(() => createDemoSlots({ default: children }), [children]);

  useComponentDemoCode(
    formatCode,
    { as: Component === 'div' ? undefined : Component, span, spanMd, spanLg },
    demoSlots,
    rootRef,
    { className, ...rest },
  );

  const rootClass = useMemo(
    () => [
      span != null && `grid_col-span-${span}`,
      spanMd != null && `grid_col-span-md-${spanMd}`,
      spanLg != null && `grid_col-span-lg-${spanLg}`,
    ],
    [span, spanMd, spanLg],
  );

  const domRest = normalizeDomProps(rest);

  return (
    <Component ref={rootRef} className={cn(rootClass, className)} {...domRest}>
      {children}
    </Component>
  );
}
