// src/components/Grid.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  cols: [Number, String],
  colsMd: [Number, String],
  colsLg: [Number, String],
  ratio: String,
  itemSpan: [Number, String],
  itemSpanMd: [Number, String],
  itemSpanLg: [Number, String],
  gap: {
    type: String,
    default: '',
    validator: (v) => ['', 'sm', 'lg', 'none'].includes(v),
  },
  autoFit: Boolean,
  autoFill: Boolean,
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('Grid', {
  booleanProps: new Set(['autoFit', 'autoFill']),
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['grid'];
  if (props.cols) classes.push(`grid_cols-${props.cols}`);
  if (props.colsMd) classes.push(`grid_cols-md-${props.colsMd}`);
  if (props.colsLg) classes.push(`grid_cols-lg-${props.colsLg}`);
  if (props.ratio) classes.push(`grid_ratio-${props.ratio}`);
  if (props.itemSpan) classes.push(`grid_item-span-${props.itemSpan}`);
  if (props.itemSpanMd) classes.push(`grid_item-span-md-${props.itemSpanMd}`);
  if (props.itemSpanLg) classes.push(`grid_item-span-lg-${props.itemSpanLg}`);
  if (props.gap === 'sm') classes.push('grid_gap-sm');
  if (props.gap === 'lg') classes.push('grid_gap-lg');
  if (props.gap === 'none') classes.push('grid_gap-none');
  if (props.autoFit) classes.push('grid_auto-fit');
  if (props.autoFill) classes.push('grid_auto-fill');
  return classes;
});
</script>

<template>
  <div ref="rootRef" v-bind="attrs" :class="rootClass">
    <slot />
  </div>
</template>

// src/components/Grid.jsx
import { useMemo, useRef } from 'react';
import { cn } from '@/utils/cn';
import { createComponentFormatter } from '@/utils/format-component-code';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';

const formatCode = createComponentFormatter('Grid', {
  booleanProps: new Set(['autoFit', 'autoFill']),
});

export default function Grid({
  cols,
  colsMd,
  colsLg,
  ratio,
  itemSpan,
  itemSpanMd,
  itemSpanLg,
  gap = '',
  autoFit,
  autoFill,
  children,
  className,
  ...rest
}) {
  const rootRef = useRef(null);
  const props = { cols, colsMd, colsLg, ratio, itemSpan, itemSpanMd, itemSpanLg, gap, autoFit, autoFill };
  const demoSlots = useMemo(() => createDemoSlots({ default: children }), [children]);

  useComponentDemoCode(formatCode, props, demoSlots, rootRef, { class: className, ...rest });

  const rootClass = cn(
    'grid',
    cols && `grid_cols-${cols}`,
    colsMd && `grid_cols-md-${colsMd}`,
    colsLg && `grid_cols-lg-${colsLg}`,
    ratio && `grid_ratio-${ratio}`,
    itemSpan && `grid_item-span-${itemSpan}`,
    itemSpanMd && `grid_item-span-md-${itemSpanMd}`,
    itemSpanLg && `grid_item-span-lg-${itemSpanLg}`,
    gap === 'sm' && 'grid_gap-sm',
    gap === 'lg' && 'grid_gap-lg',
    gap === 'none' && 'grid_gap-none',
    autoFit && 'grid_auto-fit',
    autoFill && 'grid_auto-fill',
    className,
  );

  return (
    <div ref={rootRef} className={rootClass} {...rest}>
      {children}
    </div>
  );
}
