// packages/ui/src/components/MenuGroup.vue
<script setup>
import { ref } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const props = defineProps({
  title: {
    type: String,
    required: true,
  },
});

const rootRef = ref(null);
const formatCode = createComponentFormatter('MenuGroup', { selfClosing: true });

useComponentDemoCode(formatCode, props, {}, rootRef, {});
</script>

<template>
  <li ref="rootRef" class="menu_group" role="presentation">
    <span class="menu_group-title">{{ title }}</span>
  </li>
</template>

// src/components/MenuGroup.jsx
import { useRef } from 'react';
import { createComponentFormatter } from '@/utils/format-component-code';
import { useComponentDemoCode } from '@/hooks/useDemoCode';

const formatCode = createComponentFormatter('MenuGroup', { selfClosing: true });

export default function MenuGroup({ title }) {
  const rootRef = useRef(null);

  useComponentDemoCode(formatCode, { title }, {}, rootRef, {});

  return (
    <li ref={rootRef} className="menu_group" role="presentation">
      <span className="menu_group-title">{title}</span>
    </li>
  );
}
