// src/components/MenuDivider.jsx
import { useRef } from 'react';
import { createComponentFormatter } from '@/utils/format-component-code';
import { useComponentDemoCode } from '@/hooks/useDemoCode';

const formatCode = createComponentFormatter('MenuDivider', { selfClosing: true });

export default function MenuDivider() {
  const rootRef = useRef(null);

  useComponentDemoCode(formatCode, {}, {}, rootRef, {});

  return <li ref={rootRef} className="menu_divider" role="separator" />;
}

// src/components/MenuDivider.vue
<script setup>
import { ref } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const rootRef = ref(null);
const formatCode = createComponentFormatter('MenuDivider', { selfClosing: true });

useComponentDemoCode(formatCode, {}, {}, rootRef, {});
</script>

<template>
  <li ref="rootRef" class="menu_divider" role="separator" />
</template>
