// packages/ui-react/src/components/MenuGroup.jsx
import { useRef } from 'react';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('MenuGroup', { selfClosing: true });

export default function MenuGroup({ title, className, ...rest }) {
  const rootRef = useRef(null);

  useComponentDemoCode(
    formatCode,
    { title },
    createDemoSlots({}),
    rootRef,
    { className, ...rest },
  );

  return (
    <li ref={rootRef} className={cn('menu_group', className)} role="presentation" {...rest}>
      <span className="menu_group-title">{title}</span>
    </li>
  );
}

// src/components/MenuGroup.vue
<script setup>
import { computed, ref, useAttrs } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  title: {
    type: String,
    required: true,
  },
});

const rootRef = ref(null);
const attrs = useAttrs();
const formatCode = createComponentFormatter('MenuGroup', { selfClosing: true });

useComponentDemoCode(formatCode, props, {}, rootRef, attrs);

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <li ref="rootRef" v-bind="fallthroughAttrs" :class="['menu_group', attrs.class]" role="presentation">
    <span class="menu_group-title">{{ title }}</span>
  </li>
</template>
