// packages/ui-react/src/components/Radio.jsx
import { useMemo, useRef } from 'react';
import { useRipple } from '@/hooks/useRipple';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('Radio', {
  booleanProps: new Set(['checked', 'disabled', 'labelEnd', 'button', 'ripple']),
  selfClosing: true,
});

export default function Radio({
  ripple,
  label,
  name,
  checked,
  defaultChecked,
  disabled,
  value,
  labelEnd,
  button,
  ariaLabel,
  children,
  className,
  onChange,
  id,
  ...rest
}) {
  const { rippleAttrs } = useRipple({ ripple }, { defaultEnabled: false });
  const rootRef = useRef(null);

  const labelContent = children ?? label;
  const hasLabel = Boolean(label) || (children != null && children !== '');
  const isStandalone = !hasLabel;

  const interactiveRippleAttrs = useMemo(() => {
    if (ripple === false) return { 'data-ripple': 'false' };
    if (ripple === true || isStandalone || button) {
      return { 'data-ripple': 'true' };
    }
    return {};
  }, [ripple, isStandalone, button]);

  useComponentDemoCode(
    formatCode,
    {
      ripple,
      label,
      name,
      checked,
      disabled,
      value,
      labelEnd,
      button,
      ariaLabel,
    },
    createDemoSlots({ default: labelContent }),
    rootRef,
    { className, id, onChange, ...rest },
  );

  const rootClass = useMemo(() => {
    const classes = ['radio'];
    if (labelEnd) classes.push('radio_label-end');
    if (button) classes.push('radio_button');
    return classes;
  }, [labelEnd, button]);

  const { class: _ignoredClassAttr, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  const inputCheckedProps =
    onChange != null
      ? { checked: Boolean(checked), onChange }
      : checked != null
        ? { defaultChecked: Boolean(checked) }
        : defaultChecked != null
          ? { defaultChecked: Boolean(defaultChecked) }
          : {};

  const inputEl = (
    <input
      id={id}
      type="radio"
      className="radio_input"
      name={name}
      value={value}
      disabled={disabled}
      {...inputCheckedProps}
      {...domRest}
    />
  );

  if (isStandalone) {
    return (
      <label
        ref={rootRef}
        className={cn('radio_control', className)}
        aria-label={ariaLabel}
        {...interactiveRippleAttrs}
      >
        {inputEl}
        <span className="radio_box" aria-hidden="true" />
      </label>
    );
  }

  if (button) {
    return (
      <label
        ref={rootRef}
        className={cn(rootClass, className)}
        {...interactiveRippleAttrs}
      >
        {inputEl}
        <span className="radio_label">{labelContent}</span>
      </label>
    );
  }

  return (
    <label ref={rootRef} className={cn(rootClass, className)} {...rippleAttrs}>
      {labelEnd ? <span className="radio_label">{labelContent}</span> : null}
      <span className="radio_control">
        {inputEl}
        <span className="radio_box" aria-hidden="true" />
      </span>
      {!labelEnd ? <span className="radio_label">{labelContent}</span> : null}
    </label>
  );
}

// src/components/Radio.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  label: String,
  name: String,
  checked: Boolean,
  disabled: Boolean,
  value: String,
  labelEnd: Boolean,
  button: Boolean,
  ariaLabel: String,
});
const { rippleAttrs } = useRipple(props, { defaultEnabled: false });

const interactiveRippleAttrs = computed(() => {
  if (props.ripple === false) return { 'data-ripple': 'false' };
  if (props.ripple === true || isStandalone.value || props.button) {
    return { 'data-ripple': 'true' };
  }
  return {};
});


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('Radio', {
  booleanProps: new Set(['checked', 'disabled', 'labelEnd', 'button', 'ripple']),
  selfClosing: true,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['radio'];
  if (props.labelEnd) classes.push('radio_label-end');
  if (props.button) classes.push('radio_button');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const hasLabel = computed(() => Boolean(props.label || slots.default));
const isStandalone = computed(() => !hasLabel.value);

const inputAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});
</script>

<template>
  <label v-if="isStandalone" ref="rootRef"
    v-bind="interactiveRippleAttrs" class="radio_control" :aria-label="ariaLabel">
    <input
      type="radio"
      class="radio_input"
      :name="name"
      :value="value"
      :checked="checked"
      :disabled="disabled"
      v-bind="inputAttrs"
    />
    <span class="radio_box" aria-hidden="true" />
  </label>
  <label v-else-if="button" ref="rootRef" v-bind="interactiveRippleAttrs" :class="rootClass">
    <input
      type="radio"
      class="radio_input"
      :name="name"
      :value="value"
      :checked="checked"
      :disabled="disabled"
      v-bind="inputAttrs"
    />
    <span class="radio_label">
      <slot>{{ label }}</slot>
    </span>
  </label>
  <label v-else ref="rootRef" v-bind="rippleAttrs" :class="rootClass">
    <span v-if="labelEnd" class="radio_label">
      <slot>{{ label }}</slot>
    </span>
    <span class="radio_control">
      <input
        type="radio"
        class="radio_input"
        :name="name"
        :value="value"
        :checked="checked"
        :disabled="disabled"
        v-bind="inputAttrs"
      />
      <span class="radio_box" aria-hidden="true" />
    </span>
    <span v-if="!labelEnd" class="radio_label">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>
