// src/components/Slider.jsx
import { useEffect, useMemo, useRef, useState } from 'react';
import Button from '@/components/Button.jsx';
import Icon from '@/components/Icon.jsx';
import { cn } from '@/utils/cn';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { useRipple } from '@/hooks/useRipple';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const formatCode = createComponentFormatter('Slider', {
  defaults: { min: 0, max: 100, value: 50, size: 'md' },
  booleanProps: new Set(['disabled', 'vertical', 'showValue', 'stepper', 'stepperAlways']),
  skipProps: ['modelValue'],
  selfClosing: true,
});

export default function Slider({
  ripple,
  min = 0,
  max = 100,
  value = 50,
  step,
  disabled = false,
  vertical = false,
  label,
  showValue = false,
  stepper = false,
  stepperAlways = false,
  valueSuffix,
  hint,
  decreaseLabel,
  increaseLabel,
  size = 'md',
  modelValue,
  onUpdateModelValue,
  children,
  className,
  ...rest
}) {
  const props = {
    ripple,
    min,
    max,
    value,
    step,
    disabled,
    vertical,
    label,
    showValue,
    stepper,
    stepperAlways,
    valueSuffix,
    hint,
    decreaseLabel,
    increaseLabel,
    size,
    modelValue,
  };
  const { rippleAttrs, childRippleAttrs } = useRipple(props, { mode: 'container' });
  const rootRef = useRef(null);
  const inputId = useMemo(() => `slider-${Math.random().toString(36).slice(2, 9)}`, []);
  const demoSlots = useMemo(() => createDemoSlots({ default: children }), [children]);

  useComponentDemoCode(formatCode, props, demoSlots, rootRef, { class: className, ...rest });

  const currentValue = modelValue ?? value;
  const [rangeValue, setRangeValue] = useState(currentValue);

  useEffect(() => {
    setRangeValue(currentValue);
  }, [currentValue]);

  const displayValue = `${rangeValue}${valueSuffix ?? ''}`;

  const rootClass = cn(
    'slider',
    size === 'sm' && 'slider_sm',
    size === 'lg' && 'slider_lg',
    vertical && 'slider_vertical',
    stepper && 'slider_stepper',
    stepperAlways && 'slider_stepper_always',
    className,
  );

  const adjustValue = (delta) => {
    const stepVal = step ?? 1;
    const next = Math.min(max, Math.max(min, rangeValue + delta * stepVal));
    setRangeValue(next);
    onUpdateModelValue?.(next);
  };

  const handleRangeChange = (event) => {
    const next = Number(event.target.value);
    setRangeValue(next);
    onUpdateModelValue?.(next);
  };

  const domRest = normalizeDomProps(rest);

  const rangeInput = (
    <input
      id={inputId}
      type="range"
      className="slider_input"
      min={min}
      max={max}
      step={step}
      value={rangeValue}
      disabled={disabled}
      onChange={handleRangeChange}
      {...domRest}
    />
  );

  return (
    <div ref={rootRef} className={rootClass} {...rippleAttrs}>
      {(label || showValue) && (
        <div className="slider_header">
          {label && (
            <label className="slider_label" htmlFor={inputId}>
              {label}
            </label>
          )}
          {showValue && (
            <output className="slider_value" htmlFor={inputId}>
              {displayValue}
            </output>
          )}
        </div>
      )}
      {stepper ? (
        <div className="slider_control">
          <Button
            {...childRippleAttrs}
            variant="ghost"
            size="sm"
            iconOnly
            className="slider_step slider_step-decrease"
            aria-label={decreaseLabel || '값 줄이기'}
            disabled={disabled}
            onClick={() => adjustValue(-1)}
            iconBefore={<Icon name="minus" size="sm" className="slider_step-icon" />}
          />
          {rangeInput}
          <Button
            {...childRippleAttrs}
            variant="ghost"
            size="sm"
            iconOnly
            className="slider_step slider_step-increase"
            aria-label={increaseLabel || '값 늘리기'}
            disabled={disabled}
            onClick={() => adjustValue(1)}
            iconBefore={<Icon name="plus" size="sm" className="slider_step-icon" />}
          />
        </div>
      ) : (
        rangeInput
      )}
      {hint && <p className="slider_hint">{hint}</p>}
      {children}
    </div>
  );
}

// src/components/Slider.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import Button from '@/components/Button.vue';
import Icon from '@/components/Icon.vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  min: {
    type: Number,
    default: 0,
  },
  max: {
    type: Number,
    default: 100,
  },
  value: {
    type: Number,
    default: 50,
  },
  step: Number,
  disabled: Boolean,
  vertical: Boolean,
  label: String,
  showValue: Boolean,
  stepper: Boolean,
  stepperAlways: Boolean,
  valueSuffix: String,
  hint: String,
  decreaseLabel: String,
  increaseLabel: String,
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  modelValue: Number,
});
const { rippleAttrs, childRippleAttrs } = useRipple(props, { mode: 'container' });


const emit = defineEmits(['update:modelValue']);

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const inputId = `slider-${Math.random().toString(36).slice(2, 9)}`;

const formatCode = createComponentFormatter('Slider', {
  defaults: { min: 0, max: 100, value: 50, size: 'md' },
  booleanProps: new Set(['disabled', 'vertical', 'showValue', 'stepper', 'stepperAlways']),
  skipProps: ['modelValue'],
  selfClosing: true,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const currentValue = computed(() => props.modelValue ?? props.value);

const rootClass = computed(() => {
  const classes = ['slider'];
  if (props.size === 'sm') classes.push('slider_sm');
  if (props.size === 'lg') classes.push('slider_lg');
  if (props.vertical) classes.push('slider_vertical');
  if (props.stepper) classes.push('slider_stepper');
  if (props.stepperAlways) classes.push('slider_stepper_always');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const displayValue = computed(() => {
  const suffix = props.valueSuffix ?? '';
  return `${currentValue.value}${suffix}`;
});

function adjustValue(delta) {
  const step = props.step ?? 1;
  const next = Math.min(props.max, Math.max(props.min, currentValue.value + delta * step));
  emit('update:modelValue', next);
}

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});

function onInput(event) {
  emit('update:modelValue', Number(event.target.value));
}
</script>

<template>
  <div ref="rootRef" :class="rootClass"
    v-bind="rippleAttrs"
  >
    <div v-if="label || showValue" class="slider_header">
      <label v-if="label" class="slider_label" :for="inputId">{{ label }}</label>
      <output v-if="showValue" class="slider_value" :for="inputId">{{ displayValue }}</output>
    </div>
    <div v-if="stepper" class="slider_control">
      <Button
        v-bind="childRippleAttrs"
        variant="ghost"
        size="sm"
        icon-only
        class="slider_step slider_step-decrease"
        :aria-label="decreaseLabel || '값 줄이기'"
        :disabled="disabled"
        @click="adjustValue(-1)"
      >
        <template #icon-before>
          <Icon name="minus" size="sm" class="slider_step-icon" />
        </template>
      </Button>
      <input
        :id="inputId"
        type="range"
        class="slider_input"
        :min="min"
        :max="max"
        :step="step"
        :value="currentValue"
        :disabled="disabled"
        v-bind="fallthroughAttrs"
        @input="onInput"
      />
      <Button
        v-bind="childRippleAttrs"
        variant="ghost"
        size="sm"
        icon-only
        class="slider_step slider_step-increase"
        :aria-label="increaseLabel || '값 늘리기'"
        :disabled="disabled"
        @click="adjustValue(1)"
      >
        <template #icon-before>
          <Icon name="plus" size="sm" class="slider_step-icon" />
        </template>
      </Button>
    </div>
    <input
      v-else
      :id="inputId"
      type="range"
      class="slider_input"
      :min="min"
      :max="max"
      :step="step"
      :value="currentValue"
      :disabled="disabled"
      v-bind="fallthroughAttrs"
      @input="onInput"
    />
    <p v-if="hint" class="slider_hint">{{ hint }}</p>
    <slot />
  </div>
</template>
