// packages/ui-react/src/components/SpinWrap.jsx
import { useMemo, useRef } from 'react';
import Spin from '@/components/Spin.jsx';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const formatCode = createComponentFormatter('SpinWrap', {
  booleanProps: new Set(['loading', 'block', 'blur']),
  selfClosing: false,
});

export default function SpinWrap({
  loading,
  block,
  blur,
  tip,
  ariaLabel = '로딩 중',
  children,
  className,
  style,
  ...rest
}) {
  const rootRef = useRef(null);

  useComponentDemoCode(
    formatCode,
    { loading, block, blur, tip, ariaLabel },
    createDemoSlots({ default: children }),
    rootRef,
    { className, style, ...rest },
  );

  const rootClass = useMemo(() => {
    const classes = ['spin_wrap'];
    if (block) classes.push('spin_wrap-block');
    if (blur) classes.push('spin_wrap-blur');
    if (loading) classes.push('is-loading');
    return classes;
  }, [block, blur, loading]);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  return (
    <div ref={rootRef} className={cn(rootClass, className)} style={style} {...domRest}>
      <div className="spin_wrap-body">{children}</div>
      {loading ? <Spin overlay tip={tip} ariaLabel={ariaLabel} /> : null}
    </div>
  );
}

// src/components/SpinWrap.vue
<script setup>
import Spin from '@/components/Spin.vue';
import { computed, ref } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const props = defineProps({
  loading: Boolean,
  block: Boolean,
  blur: Boolean,
  tip: String,
  ariaLabel: {
    type: String,
    default: '로딩 중',
  },
});

const rootRef = ref(null);
const formatCode = createComponentFormatter('SpinWrap', {
  booleanProps: new Set(['loading', 'block', 'blur']),
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, {}, rootRef, {});

const rootClass = computed(() => [
  'spin_wrap',
  {
    'spin_wrap-block': props.block,
    'spin_wrap-blur': props.blur,
    'is-loading': props.loading,
  },
]);
</script>

<template>
  <div ref="rootRef" :class="rootClass">
    <div class="spin_wrap-body">
      <slot />
    </div>
    <Spin v-if="loading" overlay :tip="tip" :aria-label="ariaLabel" />
  </div>
</template>
