// src/components/Spin.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  tip: String,
  color: {
    type: String,
    default: 'primary',
  },
  inline: Boolean,
  block: Boolean,
  overlay: Boolean,
  ariaLabel: {
    type: String,
    default: '로딩 중',
  },
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('Spin', {
  defaults: { size: 'md', color: 'primary' },
  booleanProps: new Set(['inline', 'block', 'overlay']),
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['spin', `color_${props.color}`];
  if (props.size === 'sm') classes.push('spin_sm');
  if (props.size === 'lg') classes.push('spin_lg');
  if (props.inline) classes.push('spin_inline');
  if (props.block) classes.push('spin_block');
  if (props.overlay) classes.push('spin_overlay');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});
</script>

<template>
  <div
    ref="rootRef"
    :class="rootClass"
    role="status"
    aria-live="polite"
    aria-busy="true"
    :aria-label="ariaLabel"
  >
    <span class="spin_indicator" aria-hidden="true" />
    <p v-if="tip" class="spin_tip">{{ tip }}</p>
    <slot />
  </div>
</template>

// src/components/Spin.jsx
import { useMemo, useRef } from 'react';
import { cn } from '@/utils/cn';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const formatCode = createComponentFormatter('Spin', {
  defaults: { size: 'md', color: 'primary' },
  booleanProps: new Set(['inline', 'block', 'overlay']),
  selfClosing: false,
});

export default function Spin({
  size = 'md',
  tip,
  color = 'primary',
  inline = false,
  block = false,
  overlay = false,
  ariaLabel = '로딩 중',
  children,
  className,
  ...rest
}) {
  const props = { size, tip, color, inline, block, overlay, ariaLabel };
  const rootRef = useRef(null);
  const demoSlots = useMemo(() => createDemoSlots({ default: children }), [children]);

  useComponentDemoCode(formatCode, props, demoSlots, rootRef, { class: className, ...rest });

  const rootClass = cn(
    'spin',
    `color_${color}`,
    size === 'sm' && 'spin_sm',
    size === 'lg' && 'spin_lg',
    inline && 'spin_inline',
    block && 'spin_block',
    overlay && 'spin_overlay',
    className,
  );

  const Root = inline ? 'span' : 'div';

  return (
    <Root
      ref={rootRef}
      className={rootClass}
      role="status"
      aria-live="polite"
      aria-busy="true"
      aria-label={ariaLabel}
    >
      <span className="spin_indicator" aria-hidden="true" />
      {tip && <span className="spin_tip">{tip}</span>}
      {children}
    </Root>
  );
}
