// src/components/Steps.vue
<script setup>
import { computed, provide, ref, useAttrs, useSlots } from 'vue';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  current: Number,
  direction: {
    type: String,
    default: 'horizontal',
    validator: (v) => ['horizontal', 'vertical'].includes(v),
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  dot: Boolean,
  iconStyle: Boolean,
  navigable: Boolean,
  align: {
    type: String,
    default: '',
    validator: (v) => ['', 'center'].includes(v),
  },
  ariaLabel: String,
});

const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const items = new Map();
const itemOrder = ref([]);

const formatCode = createComponentFormatter('Steps', {
  defaults: { direction: 'horizontal', size: 'md' },
  booleanProps: new Set(['dot', 'iconStyle', 'navigable']),
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['steps'];
  if (props.direction === 'vertical') classes.push('steps_vertical');
  if (props.size === 'sm') classes.push('steps_sm');
  if (props.size === 'lg') classes.push('steps_lg');
  if (props.dot) classes.push('steps_dot');
  if (props.iconStyle) classes.push('steps_icon-style');
  if (props.navigable) classes.push('steps_navigable');
  if (props.align === 'center') classes.push('steps_align-center');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});

function registerItem(id, itemProps) {
  items.set(id, itemProps);
  itemOrder.value = [...items.keys()];
}

function unregisterItem(id) {
  items.delete(id);
  itemOrder.value = [...items.keys()];
}

function isLastItem(id) {
  const order = itemOrder.value;
  return order.indexOf(id) === order.length - 1;
}

function getItemIndex(id) {
  return itemOrder.value.indexOf(id) + 1;
}

provide('steps', {
  registerItem,
  unregisterItem,
  isLastItem,
  getItemIndex,
  navigable: computed(() => props.navigable),
});
</script>

<template>
  <ol
    ref="rootRef"
    :class="rootClass"
    :aria-label="ariaLabel"
    v-bind="fallthroughAttrs"
  >
    <slot />
  </ol>
</template>

// src/components/Steps.jsx
import { useMemo, useRef, useState, useCallback } from 'react';
import { cn } from '@/utils/cn';
import { StepsProvider } from '@/context/StepsContext.jsx';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const formatCode = createComponentFormatter('Steps', {
  defaults: { direction: 'horizontal', size: 'md' },
  booleanProps: new Set(['dot', 'iconStyle', 'navigable']),
  selfClosing: false,
});

export default function Steps({
  current,
  direction = 'horizontal',
  size = 'md',
  dot = false,
  iconStyle = false,
  navigable = false,
  align = '',
  ariaLabel,
  children,
  className,
  ...rest
}) {
  const props = { current, direction, size, dot, iconStyle, navigable, align, ariaLabel };
  const rootRef = useRef(null);
  const [itemOrder, setItemOrder] = useState([]);
  const itemsRef = useRef(new Map());
  const demoSlots = useMemo(() => createDemoSlots({ default: children }), [children]);

  useComponentDemoCode(formatCode, props, demoSlots, rootRef, { class: className, ...rest });

  const syncItemOrder = useCallback(() => {
    setItemOrder((prev) => {
      const next = [...itemsRef.current.keys()];
      if (prev.length === next.length && prev.every((id, i) => id === next[i])) {
        return prev;
      }
      return next;
    });
  }, []);

  const registerItem = useCallback((id, itemProps) => {
    itemsRef.current.set(id, itemProps);
    syncItemOrder();
  }, [syncItemOrder]);

  const unregisterItem = useCallback((id) => {
    itemsRef.current.delete(id);
    syncItemOrder();
  }, [syncItemOrder]);

  const isLastItem = useCallback(
    (id) => {
      const order = itemOrder;
      return order.indexOf(id) === order.length - 1;
    },
    [itemOrder],
  );

  const getItemIndex = useCallback(
    (id) => itemOrder.indexOf(id) + 1,
    [itemOrder],
  );

  const contextValue = useMemo(
    () => ({
      registerItem,
      unregisterItem,
      isLastItem,
      getItemIndex,
      navigable,
    }),
    [registerItem, unregisterItem, isLastItem, getItemIndex, navigable],
  );

  const rootClass = cn(
    'steps',
    direction === 'vertical' && 'steps_vertical',
    size === 'sm' && 'steps_sm',
    size === 'lg' && 'steps_lg',
    dot && 'steps_dot',
    iconStyle && 'steps_icon-style',
    navigable && 'steps_navigable',
    align === 'center' && 'steps_align-center',
    className,
  );

  return (
    <StepsProvider value={contextValue}>
      <ol ref={rootRef} className={rootClass} aria-label={ariaLabel} {...rest}>
        {children}
      </ol>
    </StepsProvider>
  );
}
