// packages/ui/src/components/Switch.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  label: String,
  checked: Boolean,
  disabled: Boolean,
  labelEnd: Boolean,
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  ariaLabel: String,
});
const { rippleAttrs } = useRipple(props);


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);

const formatCode = createComponentFormatter('Switch', {
  defaults: { size: 'md' },
  booleanProps: new Set(['checked', 'disabled', 'labelEnd', 'ripple']),
  selfClosing: false,
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

const rootClass = computed(() => {
  const classes = ['switch'];
  if (props.labelEnd) classes.push('switch_label-end');
  if (props.size === 'sm') classes.push('switch_sm');
  if (props.size === 'lg') classes.push('switch_lg');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const hasLabel = computed(() => Boolean(props.label || slots.default));
</script>

<template>
  <label ref="rootRef"
    v-bind="rippleAttrs" :class="rootClass" :aria-label="!hasLabel ? ariaLabel : undefined">
    <span v-if="hasLabel && labelEnd" class="switch_label">
      <slot>{{ label }}</slot>
    </span>
    <span class="switch_control">
      <input
        type="checkbox"
        class="switch_input"
        role="switch"
        :checked="checked"
        :disabled="disabled"
        :aria-label="!hasLabel ? ariaLabel : undefined"
        v-bind="attrs"
      />
      <span class="switch_track" aria-hidden="true"><span class="switch_thumb" /></span>
    </span>
    <span v-if="hasLabel && !labelEnd" class="switch_label">
      <slot>{{ label }}</slot>
    </span>
  </label>
</template>

// src/components/Switch.jsx
import { useMemo, useRef } from 'react';
import { cn } from '@/utils/cn';
import { getCheckedInputProps } from '@/utils/checked-input-props';
import { useRipple } from '@/hooks/useRipple';
import { createDemoSlots, useComponentDemoCode } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

const formatCode = createComponentFormatter('Switch', {
  defaults: { size: 'md' },
  booleanProps: new Set(['checked', 'disabled', 'labelEnd', 'ripple']),
  selfClosing: false,
});

export default function Switch({
  ripple,
  label,
  checked = false,
  disabled = false,
  labelEnd = false,
  size = 'md',
  ariaLabel,
  children,
  className,
  ...rest
}) {
  const props = { ripple, label, checked, disabled, labelEnd, size, ariaLabel };
  const { rippleAttrs } = useRipple(props);
  const rootRef = useRef(null);
  const demoSlots = useMemo(
    () => createDemoSlots({ default: children ?? label }),
    [children, label],
  );

  useComponentDemoCode(formatCode, props, demoSlots, rootRef, { class: className, ...rest });

  const hasLabel = Boolean(label || children);

  const rootClass = cn(
    'switch',
    labelEnd && 'switch_label-end',
    size === 'sm' && 'switch_sm',
    size === 'lg' && 'switch_lg',
    className,
  );

  const inputProps = getCheckedInputProps(checked, rest);

  return (
    <label
      ref={rootRef}
      {...rippleAttrs}
      className={rootClass}
      aria-label={!hasLabel ? ariaLabel : undefined}
    >
      {hasLabel && labelEnd && <span className="switch_label">{children ?? label}</span>}
      <span className="switch_control">
        <input
          type="checkbox"
          className="switch_input"
          role="switch"
          disabled={disabled}
          aria-label={!hasLabel ? ariaLabel : undefined}
          {...inputProps}
        />
        <span className="switch_track" aria-hidden="true">
          <span className="switch_thumb" />
        </span>
      </span>
      {hasLabel && !labelEnd && <span className="switch_label">{children ?? label}</span>}
    </label>
  );
}
