// src/components/Tabs.vue
<script setup>
import {
  computed,
  isRef,
  provide,
  ref,
  toRef,
  unref,
  useAttrs,
  useId,
  useSlots,
  watch,
  watchEffect,
} from 'vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useTabsDemoCode } from '@/composables/useDemoCode';
import { useTabsIndicator } from '@/composables/useTabsIndicator';
import { useTabsScroll } from '@/composables/useTabsScroll';
import Button from '@/components/Button.vue';
import Icon from '@/components/Icon.vue';
import TabsTab from '@/components/TabsTab.vue';

defineOptions({ inheritAttrs: false });

const VALID_MODES = new Set(['panels', 'dynamic']);
const VALID_VARIANTS = new Set(['line', 'card', 'pill']);
const VALID_SIZES = new Set(['sm', 'md', 'lg']);
const VALID_LAYOUTS = new Set(['auto', 'equal', 'scroll']);
const VALID_INDICATORS = new Set(['static', 'slide']);

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  /** panels: 탭마다 패널 · dynamic: 단일 패널에 콘텐츠 전환 */
  mode: {
    type: String,
    default: 'panels',
    validator: (v) => ['panels', 'dynamic'].includes(v),
  },
  /** mode="dynamic"일 때 선택된 탭 key (v-model) */
  modelValue: {
    type: [String, Number],
    default: undefined,
  },
  variant: {
    type: String,
    default: 'line',
    validator: (v) => ['line', 'card', 'pill'].includes(v),
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  /** auto: 콘텐츠 너비 · equal: 100% 균등 분할 · scroll: 넘침 시 좌우 네비 스크롤 */
  layout: {
    type: String,
    default: 'auto',
    validator: (v) => ['auto', 'equal', 'scroll'].includes(v),
  },
  vertical: Boolean,
  scrollable: Boolean,
  ariaLabel: String,
  items: Array,
  indicator: {
    type: String,
    default: 'static',
    validator: (v) => ['static', 'slide'].includes(v),
  },
});

const emit = defineEmits(['update:modelValue']);
const { rippleAttrs, childRippleAttrs } = useRipple(props, { mode: 'container' });


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const listRef = ref(null);
const tabs = new Map();
const registeredTabs = ref([]);
const dynamicPanelId = useId().replace(/:/g, '');
const activeKey = ref(null);
const itemsActiveKey = ref(null);

const resolvedMode = computed(() =>
  VALID_MODES.has(props.mode) ? props.mode : 'panels'
);
const resolvedVariant = computed(() =>
  VALID_VARIANTS.has(props.variant) ? props.variant : 'line'
);
const resolvedSize = computed(() => (VALID_SIZES.has(props.size) ? props.size : 'md'));
const resolvedLayout = computed(() =>
  VALID_LAYOUTS.has(props.layout) ? props.layout : 'auto'
);
const resolvedIndicator = computed(() =>
  VALID_INDICATORS.has(props.indicator) ? props.indicator : 'static'
);

useTabsDemoCode(
  () => ({
    ...props,
    mode: resolvedMode.value,
    variant: resolvedVariant.value,
    size: resolvedSize.value,
    layout: resolvedLayout.value,
    indicator: resolvedIndicator.value,
  }),
  rootRef,
  attrs
);

const isDynamicMode = computed(() => resolvedMode.value === 'dynamic');
const isScrollNavLayout = computed(() => resolvedLayout.value === 'scroll' && !props.vertical);
const isEqualLayout = computed(() => resolvedLayout.value === 'equal');
const isLegacyScrollable = computed(() => props.scrollable && resolvedLayout.value === 'auto');
const usesItems = computed(() => Boolean(props.items?.length));
const usesPanelItems = computed(() => usesItems.value && !isDynamicMode.value);

const tabListSize = computed(() => {
  if (usesItems.value) return props.items.length;
  return registeredTabs.value.length;
});

const rootClass = computed(() => {
  const classes = ['tabs', `tabs_${resolvedVariant.value}`];
  if (resolvedSize.value === 'sm') classes.push('tabs_sm');
  if (resolvedSize.value === 'lg') classes.push('tabs_lg');
  if (props.vertical) classes.push('tabs_vertical');
  if (isEqualLayout.value) classes.push('tabs_equal');
  if (isScrollNavLayout.value) classes.push('tabs_scroll-nav');
  if (isLegacyScrollable.value) classes.push('tabs_scrollable');
  if (isDynamicMode.value) classes.push('tabs_dynamic');
  if (resolvedIndicator.value === 'slide') classes.push('tabs_indicator-slide');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const slideIndicatorEnabled = computed(() => resolvedIndicator.value === 'slide');

const { indicatorStyle, updateIndicator } = useTabsIndicator({
  listRef,
  enabled: slideIndicatorEnabled,
  vertical: toRef(props, 'vertical'),
  variant: resolvedVariant,
  onTabsChange: () => tabListSize.value,
});

const {
  canScrollPrev,
  canScrollNext,
  hasOverflow,
  scrollPrev,
  scrollNext,
  updateScrollState,
} = useTabsScroll({
  listRef,
  enabled: isScrollNavLayout,
  onTabsChange: () => tabListSize.value,
});

const fallthroughAttrs = computed(() => {
  const { class: _class, ...rest } = attrs;
  return rest;
});

function resolveItemKey(item, index) {
  return item.key ?? item.value ?? index;
}

function registerTab(tab) {
  if (isDynamicMode.value || tab.menuOnly) {
    tab.panelId = dynamicPanelId;
  }
  tabs.set(tab.id, tab);
  registeredTabs.value = [...tabs.values()];
}

function unregisterTab(id) {
  tabs.delete(id);
  registeredTabs.value = [...tabs.values()];
}

function getTabActive(tab) {
  if (isDynamicMode.value) {
    return (tab.value ?? tab.id) === activeKey.value;
  }
  return unref(tab.isActive);
}

function setTabActive(tab, value) {
  if (isRef(tab.isActive)) {
    tab.isActive.value = value;
    return;
  }

  tab.isActive = value;
}

function selectDynamicKey(key) {
  activeKey.value = key;
  emit('update:modelValue', key);
  updateIndicator();
  updateScrollState();
}

function selectTab(id) {
  if (isDynamicMode.value) {
    if (usesItems.value) {
      const tab = dynamicItemTabs.value.find((item) => item.id === id);
      if (tab && !tab.disabled) {
        selectDynamicKey(tab.key);
      }
      return;
    }

    const tab = registeredTabs.value.find((item) => item.id === id);
    if (tab && !tab.disabled) {
      selectDynamicKey(tab.value ?? tab.id);
    }
    return;
  }

  if (usesPanelItems.value) {
    const index = props.items.findIndex((_, itemIndex) => `item-tab-${itemIndex}` === id);
    const item = props.items[index];
    if (item && !item.disabled) {
      itemsActiveKey.value = resolveItemKey(item, index);
      updateIndicator();
      updateScrollState();
    }
    return;
  }

  registeredTabs.value.forEach((tab) => {
    if (!tab.disabled) {
      setTabActive(tab, tab.id === id);
    }
  });
  updateIndicator();
  updateScrollState();
}

provide('tabs', { registerTab, unregisterTab, selectTab });

watch(
  () => props.modelValue,
  (value) => {
    if (isDynamicMode.value && value != null && value !== '') {
      activeKey.value = value;
    }
  },
);

watchEffect(() => {
  if (isDynamicMode.value) {
    if (props.modelValue != null && props.modelValue !== '') {
      activeKey.value = props.modelValue;
      return;
    }

    if (usesItems.value) {
      const activeItem = props.items.find((item, index) => item.active);
      if (activeItem) {
        activeKey.value = resolveItemKey(activeItem, props.items.indexOf(activeItem));
        return;
      }
      const first = props.items.find((item) => !item.disabled);
      if (first) {
        activeKey.value = resolveItemKey(first, props.items.indexOf(first));
      }
      return;
    }

    if (!registeredTabs.value.length) return;
    const preset = registeredTabs.value.find((tab) => tab.active);
    const first = registeredTabs.value.find((tab) => !tab.disabled);
    const tab = preset || first;
    if (tab) {
      activeKey.value = tab.value ?? tab.id;
    }
    return;
  }

  if (usesPanelItems.value) {
    const currentItem = props.items.find(
      (item, index) => resolveItemKey(item, index) === itemsActiveKey.value && !item.disabled
    );
    if (currentItem) return;

    const preset = props.items.find((item) => item.active && !item.disabled);
    const first = props.items.find((item) => !item.disabled) ?? props.items[0];
    const item = preset || first;
    if (item) {
      itemsActiveKey.value = resolveItemKey(item, props.items.indexOf(item));
    }
    return;
  }

  if (!registeredTabs.value.length) return;
  const hasActive = registeredTabs.value.some((t) => getTabActive(t));
  if (!hasActive) {
    const first = registeredTabs.value.find((t) => !t.disabled);
    if (first) {
      setTabActive(first, true);
    }
  }
});

const dynamicItemTabs = computed(() => {
  if (!isDynamicMode.value || !usesItems.value) return [];
  return props.items.map((item, index) => {
    const key = resolveItemKey(item, index);
    return {
      id: `item-tab-${index}`,
      key,
      panelId: dynamicPanelId,
      label: item.label,
      disabled: item.disabled,
      isActive: activeKey.value === key,
      raw: item,
    };
  });
});

const activeDynamicItem = computed(() => {
  if (!isDynamicMode.value) return null;

  if (usesItems.value) {
    return dynamicItemTabs.value.find((tab) => tab.isActive)?.raw ?? null;
  }

  const tab = registeredTabs.value.find((item) => (item.value ?? item.id) === activeKey.value);
  if (!tab) return null;

  return {
    key: tab.value ?? tab.id,
    label: tab.label,
  };
});

const activeTabId = computed(() => {
  if (!isDynamicMode.value) return '';

  if (usesItems.value) {
    return dynamicItemTabs.value.find((tab) => tab.isActive)?.id ?? '';
  }

  return registeredTabs.value.find((tab) => (tab.value ?? tab.id) === activeKey.value)?.id ?? '';
});

const itemTabs = computed(() => {
  if (!usesPanelItems.value) return [];
  return props.items.map((item, index) => {
    const key = resolveItemKey(item, index);
    return {
      id: `item-tab-${index}`,
      panelId: `item-panel-${index}`,
      label: item.label,
      content: item.content,
      disabled: item.disabled,
      isActive: itemsActiveKey.value === key,
    };
  });
});

const barTabs = computed(() => {
  if (isDynamicMode.value && usesItems.value) {
    return dynamicItemTabs.value.map((tab) => ({
      id: tab.id,
      panelId: tab.panelId,
      label: tab.label,
      disabled: Boolean(tab.disabled),
      active: tab.isActive,
      iconSlot: null,
      badgeSlot: null,
    }));
  }

  if (usesPanelItems.value) {
    return itemTabs.value.map((tab) => ({
      id: tab.id,
      panelId: tab.panelId,
      label: tab.label,
      disabled: Boolean(tab.disabled),
      active: tab.isActive,
      iconSlot: null,
      badgeSlot: null,
    }));
  }

  return registeredTabs.value.map((tab) => ({
    id: tab.id,
    panelId: tab.panelId,
    label: tab.label,
    disabled: Boolean(tab.disabled),
    active: getTabActive(tab),
    iconSlot: tab.iconSlot ?? null,
    badgeSlot: tab.badgeSlot ?? null,
  }));
});

function handleTabKeyDown(event, currentId) {
  const enabledTabs = barTabs.value.filter((tab) => !tab.disabled);
  if (!enabledTabs.length) return;

  const currentIndex = enabledTabs.findIndex((tab) => tab.id === currentId);
  if (currentIndex === -1) return;

  let nextIndex = null;

  if (
    (!props.vertical && event.key === 'ArrowRight') ||
    (props.vertical && event.key === 'ArrowDown')
  ) {
    nextIndex = (currentIndex + 1) % enabledTabs.length;
  } else if (
    (!props.vertical && event.key === 'ArrowLeft') ||
    (props.vertical && event.key === 'ArrowUp')
  ) {
    nextIndex = (currentIndex - 1 + enabledTabs.length) % enabledTabs.length;
  } else if (event.key === 'Home') {
    nextIndex = 0;
  } else if (event.key === 'End') {
    nextIndex = enabledTabs.length - 1;
  }

  if (nextIndex == null) return;

  event.preventDefault();
  const nextTab = enabledTabs[nextIndex];
  selectTab(nextTab.id);
  [...(listRef.value?.querySelectorAll('[role="tab"]') ?? [])]
    .find((tab) => tab.id === nextTab.id)
    ?.focus();
}
</script>

<template>
  <div ref="rootRef" :class="rootClass" data-tabs v-bind="{ ...fallthroughAttrs, ...rippleAttrs }">
    <div class="tabs_bar">
      <Button
        v-if="isScrollNavLayout && hasOverflow"
        class="tabs_nav tabs_nav_prev"
        variant="outline"
        color="default"
        size="sm"
        icon-only
        :ripple="false"
        aria-label="이전 탭"
        :disabled="!canScrollPrev"
        @click="scrollPrev"
      >
        <template #icon-before>
          <Icon name="chevron-left" size="sm" />
        </template>
      </Button>

      <div class="tabs_list-wrap" :class="{ 'tabs_scroll-viewport': isScrollNavLayout }">
        <div
          ref="listRef"
          class="tabs_list"
          role="tablist"
          :aria-label="ariaLabel"
          :aria-orientation="vertical ? 'vertical' : 'horizontal'"
        >
          <span
            v-if="resolvedIndicator === 'slide'"
            v-show="indicatorStyle"
            class="tabs_indicator"
            aria-hidden="true"
            :style="indicatorStyle"
          />
          <TabsTab
            v-for="tab in barTabs"
            :key="tab.id"
            v-bind="childRippleAttrs"
            :id="tab.id"
            :panel-id="tab.panelId"
            :label="tab.label"
            :active="tab.active"
            :disabled="tab.disabled"
            :tabindex="tab.active ? 0 : -1"
            :icon-slot="tab.iconSlot"
            :badge-slot="tab.badgeSlot"
            @click="selectTab(tab.id)"
            @keydown="handleTabKeyDown($event, tab.id)"
          />
          <slot name="tabs" />
        </div>
      </div>

      <Button
        v-if="isScrollNavLayout && hasOverflow"
        class="tabs_nav tabs_nav_next"
        variant="outline"
        color="default"
        size="sm"
        icon-only
        :ripple="false"
        aria-label="다음 탭"
        :disabled="!canScrollNext"
        @click="scrollNext"
      >
        <template #icon-before>
          <Icon name="chevron-right" size="sm" />
        </template>
      </Button>

      <div v-if="$slots.extra" class="tabs_extra" data-demo-slot="extra">
        <slot name="extra" />
      </div>
    </div>
    <div class="tabs_panels" data-demo-slot="default">
      <template v-if="isDynamicMode">
        <div
          :id="dynamicPanelId"
          class="tabs_panel is-active"
          role="tabpanel"
          :aria-labelledby="activeTabId"
        >
          <slot
            name="panel"
            :item="activeDynamicItem"
            :value="activeKey"
            :active="true"
          />
        </div>
        <slot />
      </template>
      <template v-else-if="usesPanelItems">
        <div
          v-for="tab in itemTabs"
          :key="tab.panelId"
          :id="tab.panelId"
          class="tabs_panel"
          :class="{ 'is-active': tab.isActive }"
          role="tabpanel"
          :aria-labelledby="tab.id"
          :hidden="!tab.isActive || undefined"
        >
          <p>{{ tab.content }}</p>
        </div>
      </template>
      <slot v-else />
    </div>
  </div>
</template>

// src/components/Tabs.jsx
'use client';

import {
  createContext,
  useCallback,
  useEffect,
  useId,
  useMemo,
  useRef,
  useState,
} from 'react';
import Button from '@/components/Button.jsx';
import Icon from '@/components/Icon.jsx';
import TabsTab from '@/components/TabsTab.jsx';
import { useRipple } from '@/hooks/useRipple';
import { useTabsDemoCode } from '@/hooks/useDemoCode';
import { useTabsIndicator } from '@/hooks/useTabsIndicator';
import { useTabsScroll } from '@/hooks/useTabsScroll';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

export const TabsContext = createContext(null);

const VALID_MODES = new Set(['panels', 'dynamic']);
const VALID_VARIANTS = new Set(['line', 'card', 'pill']);
const VALID_SIZES = new Set(['sm', 'md', 'lg']);
const VALID_LAYOUTS = new Set(['auto', 'equal', 'scroll']);
const VALID_INDICATORS = new Set(['static', 'slide']);

function resolveItemKey(item, index) {
  return item.key ?? item.value ?? index;
}

export default function Tabs({
  ripple,
  mode = 'panels',
  value,
  defaultValue,
  variant = 'line',
  size = 'md',
  layout = 'auto',
  vertical,
  scrollable,
  ariaLabel,
  items,
  indicator = 'static',
  tabs: tabsSlot,
  extra,
  panel,
  children,
  className,
  onChange,
  ...rest
}) {
  const rootRef = useRef(null);
  const listRef = useRef(null);
  const { rippleAttrs, childRippleAttrs } = useRipple({ ripple }, { mode: 'container' });
  const reactId = useId().replace(/:/g, '');
  const dynamicPanelId = `tabs-panel-${reactId}`;

  const resolvedMode = VALID_MODES.has(mode) ? mode : 'panels';
  const resolvedVariant = VALID_VARIANTS.has(variant) ? variant : 'line';
  const resolvedSize = VALID_SIZES.has(size) ? size : 'md';
  const resolvedLayout = VALID_LAYOUTS.has(layout) ? layout : 'auto';
  const resolvedIndicator = VALID_INDICATORS.has(indicator) ? indicator : 'static';

  const isDynamicMode = resolvedMode === 'dynamic';
  const isScrollNavLayout = resolvedLayout === 'scroll' && !vertical;
  const isEqualLayout = resolvedLayout === 'equal';
  const isLegacyScrollable = scrollable && resolvedLayout === 'auto';
  const usesItems = Boolean(items?.length);
  const usesPanelItems = usesItems && !isDynamicMode;

  const [registeredTabs, setRegisteredTabs] = useState([]);
  const [activePanelId, setActivePanelId] = useState(null);
  const [activeDynamicKey, setActiveDynamicKey] = useState(() => {
    if (value != null && value !== '') return value;
    if (defaultValue != null && defaultValue !== '') return defaultValue;
    return null;
  });
  const [itemsActiveKey, setItemsActiveKey] = useState(() => {
    if (!items?.length) return null;
    const activeItem = items.find((item) => item.active);
    if (activeItem) return resolveItemKey(activeItem, items.indexOf(activeItem));
    const first = items.find((item) => !item.disabled) ?? items[0];
    return first ? resolveItemKey(first, items.indexOf(first)) : null;
  });

  useTabsDemoCode(
    {
      ripple,
      mode: resolvedMode,
      value,
      variant: resolvedVariant,
      size: resolvedSize,
      layout: resolvedLayout,
      vertical,
      scrollable,
      ariaLabel,
      items,
      indicator: resolvedIndicator,
    },
    rootRef,
    { className, onChange, ...rest },
  );

  useEffect(() => {
    if (isDynamicMode && value != null && value !== '') {
      setActiveDynamicKey(value);
    }
  }, [isDynamicMode, value]);

  const registerTab = useCallback((tab) => {
    setRegisteredTabs((prev) => {
      const existing = prev.find((item) => item.id === tab.id);
      if (
        existing &&
        existing.panelId === tab.panelId &&
        existing.label === tab.label &&
        existing.active === tab.active &&
        existing.disabled === tab.disabled &&
        existing.value === tab.value &&
        existing.menuOnly === tab.menuOnly &&
        existing.icon === tab.icon &&
        existing.badge === tab.badge
      ) {
        return prev;
      }
      return [...prev.filter((item) => item.id !== tab.id), tab];
    });
  }, []);

  const unregisterTab = useCallback((id) => {
    setRegisteredTabs((prev) => {
      if (!prev.some((item) => item.id === id)) return prev;
      return prev.filter((item) => item.id !== id);
    });
  }, []);

  const tabListSize = usesItems ? items.length : registeredTabs.length;

  const { indicatorStyle, updateIndicator } = useTabsIndicator({
    listRef,
    enabled: resolvedIndicator === 'slide',
    vertical: Boolean(vertical),
    variant: resolvedVariant,
    tabCount: tabListSize,
  });

  const {
    canScrollPrev,
    canScrollNext,
    hasOverflow,
    scrollPrev,
    scrollNext,
    updateScrollState,
  } = useTabsScroll({
    listRef,
    enabled: isScrollNavLayout,
    tabCount: tabListSize,
  });

  const selectDynamicKey = useCallback(
    (key) => {
      setActiveDynamicKey(key);
      onChange?.(key);
      updateIndicator();
      updateScrollState();
    },
    [onChange, updateIndicator, updateScrollState],
  );

  const selectTab = useCallback(
    (id) => {
      if (isDynamicMode) {
        if (usesItems) {
          const index = items.findIndex((_, i) => `item-tab-${i}` === id);
          const item = items[index];
          if (item && !item.disabled) {
            selectDynamicKey(resolveItemKey(item, index));
          }
          return;
        }

        const tab = registeredTabs.find((item) => item.id === id);
        if (tab && !tab.disabled) {
          selectDynamicKey(tab.value ?? tab.id);
        }
        return;
      }

      if (usesPanelItems) {
        const index = items.findIndex((_, i) => `item-tab-${i}` === id);
        const item = items[index];
        if (item && !item.disabled) {
          setItemsActiveKey(resolveItemKey(item, index));
          updateIndicator();
          updateScrollState();
        }
        return;
      }

      const tab = registeredTabs.find((item) => item.id === id);
      if (!tab || tab.disabled) return;

      setActivePanelId(id);
      updateIndicator();
      updateScrollState();
    },
    [
      isDynamicMode,
      usesItems,
      usesPanelItems,
      items,
      registeredTabs,
      selectDynamicKey,
      updateIndicator,
      updateScrollState,
    ],
  );

  const isTabActive = useCallback(
    (id) => {
      if (isDynamicMode) return false;
      if (usesPanelItems) return false;
      return activePanelId === id;
    },
    [isDynamicMode, usesPanelItems, activePanelId],
  );

  // Initialize / sync active panel from registered TabPanels
  useEffect(() => {
    if (isDynamicMode || usesPanelItems) return;
    if (!registeredTabs.length) return;

    setActivePanelId((current) => {
      if (current && registeredTabs.some((tab) => tab.id === current && !tab.disabled)) {
        return current;
      }
      const preset = registeredTabs.find((tab) => tab.active && !tab.disabled);
      const first = registeredTabs.find((tab) => !tab.disabled);
      return (preset || first)?.id ?? null;
    });
  }, [isDynamicMode, usesPanelItems, registeredTabs]);

  // Dynamic mode: initialize active key from registered TabMenus
  useEffect(() => {
    if (!isDynamicMode || usesItems) return;
    if (value != null && value !== '') return;
    if (activeDynamicKey != null) return;
    if (!registeredTabs.length) return;

    const preset = registeredTabs.find((tab) => tab.active && !tab.disabled);
    const first = registeredTabs.find((tab) => !tab.disabled);
    const tab = preset || first;
    if (tab) setActiveDynamicKey(tab.value ?? tab.id);
  }, [isDynamicMode, usesItems, value, activeDynamicKey, registeredTabs]);


  const contextValue = useMemo(
    () => ({
      registerTab,
      unregisterTab,
      selectTab,
      isTabActive,
      isDynamicMode,
      dynamicPanelId,
    }),
    [registerTab, unregisterTab, selectTab, isTabActive, isDynamicMode, dynamicPanelId],
  );

  const dynamicItemTabs = useMemo(() => {
    if (!isDynamicMode || !usesItems) return [];
    return items.map((item, index) => {
      const key = resolveItemKey(item, index);
      return {
        id: `item-tab-${index}`,
        key,
        panelId: dynamicPanelId,
        label: item.label,
        disabled: item.disabled,
        isActive: activeDynamicKey === key,
        raw: item,
      };
    });
  }, [isDynamicMode, usesItems, items, dynamicPanelId, activeDynamicKey]);

  const activeDynamicItem = useMemo(() => {
    if (!isDynamicMode) return null;

    if (usesItems) {
      return dynamicItemTabs.find((tab) => tab.isActive)?.raw ?? null;
    }

    const tab = registeredTabs.find((item) => (item.value ?? item.id) === activeDynamicKey);
    if (!tab) return null;

    return {
      key: tab.value ?? tab.id,
      label: tab.label,
    };
  }, [isDynamicMode, usesItems, dynamicItemTabs, registeredTabs, activeDynamicKey]);

  const activeTabId = useMemo(() => {
    if (!isDynamicMode) return '';

    if (usesItems) {
      return dynamicItemTabs.find((tab) => tab.isActive)?.id ?? '';
    }

    return (
      registeredTabs.find((tab) => (tab.value ?? tab.id) === activeDynamicKey)?.id ?? ''
    );
  }, [isDynamicMode, usesItems, dynamicItemTabs, registeredTabs, activeDynamicKey]);

  const itemTabs = useMemo(() => {
    if (!usesPanelItems) return [];
    return items.map((item, index) => {
      const key = resolveItemKey(item, index);
      return {
        id: `item-tab-${index}`,
        panelId: `item-panel-${index}`,
        label: item.label,
        content: item.content,
        disabled: item.disabled,
        isActive: itemsActiveKey === key,
      };
    });
  }, [usesPanelItems, items, itemsActiveKey]);

  const barTabs = useMemo(() => {
    if (isDynamicMode && usesItems) {
      return dynamicItemTabs.map((tab) => ({
        id: tab.id,
        panelId: tab.panelId,
        label: tab.label,
        disabled: Boolean(tab.disabled),
        active: tab.isActive,
        icon: null,
        badge: null,
      }));
    }

    if (usesPanelItems) {
      return itemTabs.map((tab) => ({
        id: tab.id,
        panelId: tab.panelId,
        label: tab.label,
        disabled: Boolean(tab.disabled),
        active: tab.isActive,
        icon: null,
        badge: null,
      }));
    }

    return registeredTabs.map((tab) => ({
      id: tab.id,
      panelId: isDynamicMode ? dynamicPanelId : tab.panelId,
      label: tab.label,
      disabled: Boolean(tab.disabled),
      active: isDynamicMode
        ? (tab.value ?? tab.id) === activeDynamicKey
        : activePanelId === tab.id,
      icon: tab.icon ?? null,
      badge: tab.badge ?? null,
    }));
  }, [
    isDynamicMode,
    usesItems,
    usesPanelItems,
    dynamicItemTabs,
    itemTabs,
    registeredTabs,
    dynamicPanelId,
    activeDynamicKey,
    activePanelId,
  ]);

  const handleTabKeyDown = useCallback(
    (event, currentId) => {
      const enabledTabs = barTabs.filter((tab) => !tab.disabled);
      if (!enabledTabs.length) return;

      const currentIndex = enabledTabs.findIndex((tab) => tab.id === currentId);
      if (currentIndex === -1) return;

      let nextIndex = null;

      if (
        (!vertical && event.key === 'ArrowRight') ||
        (vertical && event.key === 'ArrowDown')
      ) {
        nextIndex = (currentIndex + 1) % enabledTabs.length;
      } else if (
        (!vertical && event.key === 'ArrowLeft') ||
        (vertical && event.key === 'ArrowUp')
      ) {
        nextIndex = (currentIndex - 1 + enabledTabs.length) % enabledTabs.length;
      } else if (event.key === 'Home') {
        nextIndex = 0;
      } else if (event.key === 'End') {
        nextIndex = enabledTabs.length - 1;
      }

      if (nextIndex == null) return;

      event.preventDefault();
      const nextTab = enabledTabs[nextIndex];
      selectTab(nextTab.id);
      listRef.current
        ?.querySelector(`#${CSS.escape(nextTab.id)}`)
        ?.focus();
    },
    [barTabs, selectTab, vertical],
  );

  const rootClass = useMemo(() => {
    const classes = ['tabs', `tabs_${resolvedVariant}`];
    if (resolvedSize === 'sm') classes.push('tabs_sm');
    if (resolvedSize === 'lg') classes.push('tabs_lg');
    if (vertical) classes.push('tabs_vertical');
    if (isEqualLayout) classes.push('tabs_equal');
    if (isScrollNavLayout) classes.push('tabs_scroll-nav');
    if (isLegacyScrollable) classes.push('tabs_scrollable');
    if (isDynamicMode) classes.push('tabs_dynamic');
    if (resolvedIndicator === 'slide') classes.push('tabs_indicator-slide');
    return classes;
  }, [
    resolvedVariant,
    resolvedSize,
    vertical,
    isEqualLayout,
    isScrollNavLayout,
    isLegacyScrollable,
    isDynamicMode,
    resolvedIndicator,
  ]);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  const panelContent =
    typeof panel === 'function'
      ? panel({ item: activeDynamicItem, value: activeDynamicKey, active: true })
      : panel;

  return (
    <TabsContext.Provider value={contextValue}>
      <div
        ref={rootRef}
        className={cn(rootClass, className)}
        data-tabs=""
        {...rippleAttrs}
        {...domRest}
      >
        <div className="tabs_bar">
          {isScrollNavLayout && hasOverflow ? (
            <Button
              className="tabs_nav tabs_nav_prev"
              variant="outline"
              color="default"
              size="sm"
              iconOnly
              ripple={false}
              ariaLabel="이전 탭"
              disabled={!canScrollPrev}
              onClick={scrollPrev}
              iconBefore={<Icon name="chevron-left" size="sm" />}
            />
          ) : null}

          <div
            className={cn('tabs_list-wrap', isScrollNavLayout && 'tabs_scroll-viewport')}
          >
            <div
              ref={listRef}
              className="tabs_list"
              role="tablist"
              aria-label={ariaLabel}
              aria-orientation={vertical ? 'vertical' : 'horizontal'}
            >
              {resolvedIndicator === 'slide' && indicatorStyle ? (
                <span className="tabs_indicator" aria-hidden="true" style={indicatorStyle} />
              ) : null}
              {barTabs.map((tab) => (
                <TabsTab
                  key={tab.id}
                  {...childRippleAttrs}
                  id={tab.id}
                  panelId={tab.panelId}
                  label={tab.label}
                  active={tab.active}
                  disabled={tab.disabled}
                  tabIndex={tab.active ? 0 : -1}
                  icon={tab.icon}
                  badge={tab.badge}
                  onClick={() => selectTab(tab.id)}
                  onKeyDown={(event) => handleTabKeyDown(event, tab.id)}
                />
              ))}
              {tabsSlot}
            </div>
          </div>

          {isScrollNavLayout && hasOverflow ? (
            <Button
              className="tabs_nav tabs_nav_next"
              variant="outline"
              color="default"
              size="sm"
              iconOnly
              ripple={false}
              ariaLabel="다음 탭"
              disabled={!canScrollNext}
              onClick={scrollNext}
              iconBefore={<Icon name="chevron-right" size="sm" />}
            />
          ) : null}

          {extra != null ? (
            <div className="tabs_extra" data-demo-slot="extra">
              {extra}
            </div>
          ) : null}
        </div>

        <div className="tabs_panels" data-demo-slot="default">
          {isDynamicMode ? (
            <>
              <div
                id={dynamicPanelId}
                className="tabs_panel is-active"
                role="tabpanel"
                aria-labelledby={activeTabId}
              >
                {panelContent}
              </div>
              {children}
            </>
          ) : usesPanelItems ? (
            itemTabs.map((tab) => (
              <div
                key={tab.panelId}
                id={tab.panelId}
                className={cn('tabs_panel', tab.isActive && 'is-active')}
                role="tabpanel"
                aria-labelledby={tab.id}
                hidden={!tab.isActive || undefined}
              >
                <p>{tab.content}</p>
              </div>
            ))
          ) : (
            children
          )}
        </div>
      </div>
    </TabsContext.Provider>
  );
}
