// packages/ui-react/src/components/Tag.jsx
import { useMemo, useRef } from 'react';
import Button from '@/components/Button.jsx';
import Icon from '@/components/Icon.jsx';
import { useRipple } from '@/hooks/useRipple';
import { useComponentDemoCode, createDemoSlots } from '@/hooks/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';
import { normalizeDomProps } from '@/utils/normalize-dom-props';
import { cn } from '@/utils/cn';

const VALID_VARIANTS = new Set(['filled', 'solid', 'outline', 'borderless']);
const VALID_SIZES = new Set(['sm', 'md', 'lg']);

const formatCode = createComponentFormatter('Tag', {
  defaults: { color: 'primary', variant: 'filled', size: 'md' },
  booleanProps: new Set(['round', 'checkable', 'add', 'closable', 'selected', 'disabled', 'ripple']),
});

export default function Tag({
  ripple,
  color = 'primary',
  variant = 'filled',
  size = 'md',
  round,
  checkable,
  add,
  closable,
  selected,
  disabled,
  label,
  href,
  closeLabel,
  icon,
  children,
  className,
  onClose,
  onClick,
  ...rest
}) {
  const rootRef = useRef(null);
  const { childRippleAttrs } = useRipple({ ripple }, { defaultEnabled: false });
  const resolvedVariant = VALID_VARIANTS.has(variant) ? variant : 'filled';
  const resolvedSize = VALID_SIZES.has(size) ? size : 'md';

  const rootRippleAttrs = useMemo(() => {
    if (ripple === false) return { 'data-ripple': 'false' };
    if (ripple === true || checkable || add || href) {
      return { 'data-ripple': 'true' };
    }
    return {};
  }, [ripple, checkable, add, href]);

  const needsClosableSplit = Boolean(closable && (checkable || add || href));

  useComponentDemoCode(
    formatCode,
    {
      ripple,
      color,
      variant: resolvedVariant,
      size: resolvedSize,
      round,
      checkable,
      add,
      closable,
      selected,
      disabled,
      label,
      href,
      closeLabel,
    },
    createDemoSlots({ default: children, icon }),
    rootRef,
    { className, onClose, onClick, ...rest },
  );

  const rootClass = useMemo(() => {
    const classes = ['tag', `color_${color}`];
    if (resolvedVariant === 'solid') classes.push('tag_solid');
    if (resolvedVariant === 'outline') classes.push('tag_outline');
    if (resolvedVariant === 'borderless') classes.push('tag_borderless');
    if (resolvedSize === 'sm') classes.push('tag_sm');
    if (resolvedSize === 'lg') classes.push('tag_lg');
    if (round) classes.push('tag_round');
    if (checkable) classes.push('tag_checkable');
    if (add) classes.push('tag_add');
    if (selected) classes.push('is-selected');
    if (disabled) classes.push('is-disabled');
    return classes;
  }, [color, resolvedVariant, resolvedSize, round, checkable, add, selected, disabled]);

  const { class: _ignoredClass, ...restForDom } = rest;
  const domRest = normalizeDomProps(restForDom);

  const content = (
    <>
      {icon ? (
        <span className="tag_icon" aria-hidden="true">
          {icon}
        </span>
      ) : null}
      {children ?? label}
    </>
  );

  const closeButton = closable ? (
    <Button
      {...childRippleAttrs}
      variant="ghost"
      iconOnly
      className="tag_close"
      ariaLabel={closeLabel || `${label ?? ''} 태그 제거`}
      iconBefore={<Icon name="close" size="sm" />}
      onClick={(event) => {
        event.stopPropagation();
        onClose?.(event);
      }}
    />
  ) : null;

  if (needsClosableSplit) {
    const ControlTag = checkable || add ? 'button' : 'a';
    return (
      <span ref={rootRef} className={cn(rootClass, className)} {...domRest}>
        <ControlTag
          className="tag_control"
          {...rootRippleAttrs}
          type={ControlTag === 'button' ? 'button' : undefined}
          href={ControlTag === 'a' ? href : undefined}
          disabled={ControlTag === 'button' ? disabled : undefined}
          aria-pressed={checkable ? String(Boolean(selected)) : undefined}
          aria-disabled={ControlTag === 'a' && disabled ? 'true' : undefined}
          tabIndex={ControlTag === 'a' && disabled ? -1 : undefined}
          onClick={(event) => {
            if (ControlTag === 'a') event.preventDefault();
            onClick?.(event);
          }}
        >
          {content}
        </ControlTag>
        {closeButton}
      </span>
    );
  }

  const RootTag = checkable || add ? 'button' : href ? 'a' : 'span';

  return (
    <RootTag
      ref={rootRef}
      className={cn(rootClass, className)}
      {...rootRippleAttrs}
      type={RootTag === 'button' ? 'button' : undefined}
      href={href || undefined}
      disabled={disabled || undefined}
      aria-pressed={checkable ? String(Boolean(selected)) : undefined}
      onClick={(event) => {
        if (!href && RootTag !== 'button') event.preventDefault();
        onClick?.(event);
      }}
      {...domRest}
    >
      {content}
      {closeButton}
    </RootTag>
  );
}

// src/components/Tag.vue
<script setup>
import { computed, ref, useAttrs, useSlots } from 'vue';
import Button from '@/components/Button.vue';
import Icon from '@/components/Icon.vue';
import { rippleProp, useRipple } from '@/composables/useRipple';
import { useComponentDemoCode } from '@/composables/useDemoCode';
import { createComponentFormatter } from '@/utils/format-component-code';

defineOptions({ inheritAttrs: false });

const props = defineProps({
  /** 클릭 파장(ripple). true 활성 · false 비활성 · 미지정 시 컴포넌트 기본 */
  ripple: rippleProp,
  color: {
    type: String,
    default: 'primary',
  },
  variant: {
    type: String,
    default: 'filled',
    validator: (v) => ['filled', 'solid', 'outline', 'borderless'].includes(v),
  },
  size: {
    type: String,
    default: 'md',
    validator: (v) => ['sm', 'md', 'lg'].includes(v),
  },
  round: Boolean,
  checkable: Boolean,
  add: Boolean,
  closable: Boolean,
  selected: Boolean,
  disabled: Boolean,
  label: String,
  href: String,
  closeLabel: String,
});
const { childRippleAttrs } = useRipple(props, { defaultEnabled: false });

const rootRippleAttrs = computed(() => {
  if (props.ripple === false) return { 'data-ripple': 'false' };
  if (props.ripple === true || props.checkable || props.add || props.href) {
    return { 'data-ripple': 'true' };
  }
  return {};
});


const slots = useSlots();
const attrs = useAttrs();
const rootRef = ref(null);
const emit = defineEmits(['close']);

const formatCode = createComponentFormatter('Tag', {
  defaults: { color: 'primary', variant: 'filled', size: 'md' },
  booleanProps: new Set(['round', 'checkable', 'add', 'closable', 'selected', 'disabled', 'ripple']),
});

useComponentDemoCode(formatCode, props, slots, rootRef, attrs);

/** closable + button/a 루트는 interactive 중첩이 되므로 span 래퍼 + tag_control로 분리 */
const needsClosableSplit = computed(
  () => props.closable && (props.checkable || props.add || Boolean(props.href)),
);

const rootTag = computed(() => {
  if (needsClosableSplit.value) return 'span';
  if (props.checkable || props.add) return 'button';
  if (props.href) return 'a';
  return 'span';
});

const controlTag = computed(() => {
  if (props.checkable || props.add) return 'button';
  return 'a';
});

const controlRippleAttrs = computed(() => {
  if (needsClosableSplit.value) return rootRippleAttrs.value;
  return {};
});

const wrapperRippleAttrs = computed(() => {
  if (needsClosableSplit.value) return {};
  return rootRippleAttrs.value;
});

const rootClass = computed(() => {
  const classes = ['tag', `color_${props.color}`];
  if (props.variant === 'solid') classes.push('tag_solid');
  if (props.variant === 'outline') classes.push('tag_outline');
  if (props.variant === 'borderless') classes.push('tag_borderless');
  if (props.size === 'sm') classes.push('tag_sm');
  if (props.size === 'lg') classes.push('tag_lg');
  if (props.round) classes.push('tag_round');
  if (props.checkable) classes.push('tag_checkable');
  if (props.add) classes.push('tag_add');
  if (props.selected) classes.push('is-selected');
  if (props.disabled) classes.push('is-disabled');
  if (attrs.class) classes.push(attrs.class);
  return classes;
});

const buttonType = computed(() => {
  if (needsClosableSplit.value) return undefined;
  if (props.checkable || props.add) return 'button';
  return undefined;
});
</script>

<template>
  <span
    v-if="needsClosableSplit"
    ref="rootRef"
    v-bind="wrapperRippleAttrs"
    :class="rootClass"
  >
    <component
      :is="controlTag"
      class="tag_control"
      v-bind="controlRippleAttrs"
      :type="controlTag === 'button' ? 'button' : undefined"
      :href="controlTag === 'a' ? href : undefined"
      :disabled="controlTag === 'button' ? disabled : undefined"
      :aria-pressed="checkable ? String(selected) : undefined"
      :aria-disabled="controlTag === 'a' && disabled ? 'true' : undefined"
      :tabindex="controlTag === 'a' && disabled ? -1 : undefined"
      @click="controlTag === 'a' ? $event.preventDefault() : undefined"
    >
      <span v-if="$slots.icon" class="tag_icon" aria-hidden="true">
        <slot name="icon" />
      </span>
      <slot>{{ label }}</slot>
    </component>
    <Button
      v-bind="childRippleAttrs"
      variant="ghost"
      icon-only
      class="tag_close"
      :aria-label="closeLabel || `${label} 태그 제거`"
      @click.stop="emit('close', $event)"
    >
      <template #icon-before>
        <Icon name="close" size="sm" />
      </template>
    </Button>
  </span>
  <component
    v-else
    :is="rootTag"
    ref="rootRef"
    v-bind="wrapperRippleAttrs"
    :class="rootClass"
    :type="buttonType"
    :href="href || undefined"
    :disabled="disabled || undefined"
    :aria-pressed="checkable ? String(selected) : undefined"
    @click="href ? undefined : ($event) => !href && $event.preventDefault()"
  >
    <span v-if="$slots.icon" class="tag_icon" aria-hidden="true">
      <slot name="icon" />
    </span>
    <slot>{{ label }}</slot>
    <Button
      v-if="closable"
      v-bind="childRippleAttrs"
      variant="ghost"
      icon-only
      class="tag_close"
      :aria-label="closeLabel || `${label} 태그 제거`"
      @click.stop="emit('close', $event)"
    >
      <template #icon-before>
        <Icon name="close" size="sm" />
      </template>
    </Button>
  </component>
</template>
