// src/components/guide/GuideSection.jsx
import { useMemo } from 'react';
import { formatDocDescription } from '@/utils/format-doc-description';

export default function GuideSection({ title, headingId, description, children }) {
  const formattedDescription = useMemo(
    () => formatDocDescription(description),
    [description],
  );

  return (
    <section className="section" aria-labelledby={headingId}>
      <h2 id={headingId}>{title}</h2>
      {description ? (
        <p dangerouslySetInnerHTML={{ __html: formattedDescription }} />
      ) : null}
      {children}
    </section>
  );
}

// src/components/guide/GuideSection.vue
<script setup>
import { computed } from 'vue';
import { formatDocDescription } from '@/utils/format-doc-description';

const props = defineProps({
  title: {
    type: String,
    required: true,
  },
  headingId: {
    type: String,
    required: true,
  },
  description: String,
});

const formattedDescription = computed(() => formatDocDescription(props.description));
</script>

<template>
  <section class="section" :aria-labelledby="headingId">
    <h2 :id="headingId">{{ title }}</h2>
    <p v-if="description" v-html="formattedDescription" />
    <slot />
  </section>
</template>
