// apps/angular/src/components/layout/Divider/divider.component.ts
import { Component, computed, input } from '@angular/core';

@Component({
  selector: 'Divider',
  standalone: true,
  template: `
    @switch (rootTag()) {
      @case ('hr') { <hr [class]="classes()" data-component="Divider" [attr.aria-hidden]="vertical() ? 'true' : null" /> }
      @case ('span') {
        <span [class]="classes()" data-component="Divider" [attr.aria-hidden]="vertical() ? 'true' : null">
          <ng-content>{{ label() }}</ng-content>
        </span>
      }
      @default {
        <div [class]="classes()" data-component="Divider" [attr.aria-hidden]="vertical() ? 'true' : null">
          <ng-content>{{ label() }}</ng-content>
        </div>
      }
    }
  `,
})
export class Divider {
  readonly hostClass = input<string>('');
  readonly as = input<string | undefined>(undefined);
  readonly tag = input<string>('auto');
  readonly vertical = input<boolean>(false);
  readonly dashed = input<boolean>(false);
  readonly plain = input<boolean>(false);
  readonly orient = input<string | undefined>(undefined);
  readonly orientation = input<string>('');
  readonly label = input<string | undefined>(undefined);

  private readonly orientations = new Set(['', 'left', 'right']);
  private readonly tags = new Set(['auto', 'hr', 'div', 'span']);

  readonly hasContent = computed(() => Boolean(this.label()));
  readonly resolvedOrient = computed(() => this.orient() ?? this.orientation());
  readonly resolvedTag = computed(() => (this.tags.has(this.tag()) ? this.tag() : 'auto'));
  readonly rootTag = computed(() => {
    if (this.as()) return this.as();
    if (this.resolvedTag() !== 'auto') return this.resolvedTag();
    if (this.vertical()) return 'span';
    if (this.hasContent()) return 'div';
    return 'hr';
  });

  readonly classes = computed(() =>
    [
      'divider',
      this.vertical() && 'divider_vertical',
      this.dashed() && 'divider_dashed',
      this.plain() && 'divider_plain',
      this.orientations.has(this.resolvedOrient()) &&
        this.resolvedOrient() &&
        `divider_orient-${this.resolvedOrient()}`,
      this.hostClass(),
    ]
      .filter(Boolean)
      .join(' '),
  );
}

export default Divider;

// apps/react/src/components/layout/Divider/Divider.jsx
const ORIENTATIONS = new Set(['', 'left', 'right']);
const TAGS = new Set(['auto', 'hr', 'div', 'span']);

export function Divider({
  as, tag = 'auto', vertical = false, dashed = false, plain = false, orient, orientation = '', label,
  children, className = '', ...props
}) {
  const content = children ?? label;
  const resolvedOrient = orient ?? orientation;
  const resolvedTag = TAGS.has(tag) ? tag : 'auto';
  const Root = as || (resolvedTag !== 'auto' ? resolvedTag : vertical ? 'span' : content ? 'div' : 'hr');
  const classes = [
    'divider', vertical && 'divider_vertical', dashed && 'divider_dashed',
    plain && 'divider_plain', ORIENTATIONS.has(resolvedOrient) && resolvedOrient && `divider_orient-${resolvedOrient}`,
    className
  ].filter(Boolean).join(' ');
  const accessibility = vertical ? { 'aria-hidden': 'true' } : {};

  return <Root className={classes} data-component="Divider" {...accessibility} {...props}>{Root === 'hr' ? null : content}</Root>;
}

export default Divider;
