// apps/angular/src/components/basic/Typography/typo-title.component.ts
import { Component, computed, input } from '@angular/core';

const TITLE_LEVELS = new Set([1, 2, 3, 4, 5, '1', '2', '3', '4', '5']);

@Component({
  selector: 'TypoTitle',
  standalone: true,
  template: `
    @switch (resolvedLevel()) {
      @case (1) { <h1 [class]="classes()" data-component="TypoTitle"><ng-content>{{ label() }}</ng-content></h1> }
      @case (2) { <h2 [class]="classes()" data-component="TypoTitle"><ng-content>{{ label() }}</ng-content></h2> }
      @case (3) { <h3 [class]="classes()" data-component="TypoTitle"><ng-content>{{ label() }}</ng-content></h3> }
      @case (4) { <h4 [class]="classes()" data-component="TypoTitle"><ng-content>{{ label() }}</ng-content></h4> }
      @default { <h5 [class]="classes()" data-component="TypoTitle"><ng-content>{{ label() }}</ng-content></h5> }
    }
  `,
})
export class TypoTitle {
  readonly hostClass = input<string>('');
  readonly level = input<number | string>(1);
  readonly color = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);

  readonly resolvedLevel = computed(() =>
    TITLE_LEVELS.has(this.level()) ? Number(this.level()) : 1,
  );

  readonly classes = computed(() =>
    [
      `typo_title-${this.resolvedLevel()}`,
      this.color() && `color_${this.color()}`,
      this.hostClass(),
    ]
      .filter(Boolean)
      .join(' '),
  );
}

export default TypoTitle;

// apps/vue/src/components/basic/Typography/TypoTitle.vue
<script setup>
import { computed } from 'vue';

defineOptions({ name: 'UxkmTypoTitle' });

const props = defineProps({
  level: { type: [Number, String], default: 1, validator: (value) => [1, 2, 3, 4, 5, '1', '2', '3', '4', '5'].includes(value) },
  color: String,
  label: String
});

const resolvedLevel = computed(() => [1, 2, 3, 4, 5].includes(Number(props.level)) ? Number(props.level) : 1);
const rootTag = computed(() => `h${resolvedLevel.value}`);
const classes = computed(() => [`typo_title-${resolvedLevel.value}`, props.color && `color_${props.color}`].filter(Boolean));
</script>

<template>
  <component :is="rootTag" :class="classes" data-component="TypoTitle"><slot>{{ label }}</slot></component>
</template>
