// apps/react/src/components/feedback/Progress/Progress.jsx
import { useMemo } from 'react';

const statuses = new Set(['', 'success', 'exception']);
const sizes = new Set(['sm', 'md', 'lg']);
const colors = new Set(['primary', 'success', 'warning', 'danger']);
const normalizePercent = (value) => Math.min(100, Math.max(0, Number(value) || 0));

export function Progress({ percent = 0, status = '', size = 'md', showInfo = false, label, color = 'primary', striped = false, animated = false, indeterminate = false, inside = false, block = false, ariaLabel = '진행률', className = '', ...props }) {
  const value = normalizePercent(percent);
  const resolvedStatus = statuses.has(status) ? status : '';
  const resolvedSize = sizes.has(size) ? size : 'md';
  const resolvedColor = colors.has(color) ? color : 'primary';
  const colorClass = resolvedStatus === 'success' ? 'color_success' : resolvedStatus === 'exception' ? 'color_danger' : `color_${resolvedColor}`;
  const classes = useMemo(() => ['progress', colorClass, block ? 'progress_block' : 'progress_fit', resolvedSize !== 'md' && `progress_${resolvedSize}`, striped && 'progress_striped', animated && 'progress_animated', indeterminate && 'is-indeterminate', inside && 'progress_inside', className].filter(Boolean).join(' '), [animated, block, className, colorClass, indeterminate, inside, resolvedSize, striped]);
  const displayValue = `${value}%`;
  return <div {...props} className={classes} data-component="Progress">{(showInfo || label) && <div className="progress_header">{label && <span className="progress_label">{label}</span>}{showInfo && <span className="progress_value">{displayValue}</span>}</div>}<div className="progress_track" role="progressbar" aria-valuenow={indeterminate ? undefined : value} aria-valuemin={0} aria-valuemax={100} aria-label={ariaLabel} aria-busy={indeterminate || undefined} style={inside ? { background: 'var(--color-border-subtle)' } : undefined}><span className="progress_bar" style={{ width: `${value}%` }}>{inside ? displayValue : null}</span></div></div>;
}

export default Progress;

// apps/angular/src/components/feedback/Progress/progress.component.ts
import { Component, computed, input } from '@angular/core';

const STATUSES = new Set(['', 'success', 'exception']);
const SIZES = new Set(['sm', 'md', 'lg']);
const COLORS = new Set(['primary', 'success', 'warning', 'danger']);

function normalizePercent(value: number | string | undefined): number {
  return Math.min(100, Math.max(0, Number(value) || 0));
}

@Component({
  selector: 'Progress',
  standalone: true,
  template: `
    <div [class]="classes()" data-component="Progress">
      @if (showInfo() || label()) {
        <div class="progress_header">
          @if (label()) { <span class="progress_label">{{ label() }}</span> }
          @if (showInfo()) { <span class="progress_value">{{ displayValue() }}</span> }
        </div>
      }
      <div
        class="progress_track"
        role="progressbar"
        [attr.aria-valuenow]="indeterminate() ? null : normalizedPercent()"
        aria-valuemin="0"
        aria-valuemax="100"
        [attr.aria-label]="ariaLabel()"
        [attr.aria-busy]="indeterminate() || null"
        [style.background]="inside() ? 'var(--color-border-subtle)' : null"
      >
        <span class="progress_bar" [style.width.%]="normalizedPercent()">
          @if (inside()) { {{ displayValue() }} }
        </span>
      </div>
    </div>
  `,
})
export class Progress {
  readonly hostClass = input<string>('');
  readonly percent = input<number>(0);
  readonly status = input<string>('');
  readonly size = input<string>('md');
  readonly showInfo = input<boolean>(false);
  readonly label = input<string | undefined>(undefined);
  readonly color = input<string>('primary');
  readonly striped = input<boolean>(false);
  readonly animated = input<boolean>(false);
  readonly indeterminate = input<boolean>(false);
  readonly inside = input<boolean>(false);
  readonly block = input<boolean>(false);
  readonly ariaLabel = input<string>('진행률');

  readonly normalizedPercent = computed(() => normalizePercent(this.percent()));
  readonly resolvedStatus = computed(() =>
    STATUSES.has(this.status()) ? this.status() : '',
  );
  readonly resolvedSize = computed(() => (SIZES.has(this.size()) ? this.size() : 'md'));
  readonly resolvedColor = computed(() =>
    COLORS.has(this.color()) ? this.color() : 'primary',
  );

  readonly colorClass = computed(() => {
    const status = this.resolvedStatus();
    if (status === 'success') return 'color_success';
    if (status === 'exception') return 'color_danger';
    return `color_${this.resolvedColor()}`;
  });

  readonly displayValue = computed(() => `${this.normalizedPercent()}%`);

  readonly classes = computed(() =>
    [
      'progress',
      this.colorClass(),
      this.block() ? 'progress_block' : 'progress_fit',
      this.resolvedSize() !== 'md' && `progress_${this.resolvedSize()}`,
      this.striped() && 'progress_striped',
      this.animated() && 'progress_animated',
      this.indeterminate() && 'is-indeterminate',
      this.inside() && 'progress_inside',
      this.hostClass(),
    ]
      .filter(Boolean)
      .join(' '),
  );
}

export default Progress;
